services:
  colver:
    build: .
    ports:
      - "8002:8000"
    volumes:
      - ./models:/app/models
      - ./data:/app/data
    environment:
      - ROOT_PATH=${ROOT_PATH:-/colver}
    restart: unless-stopped
