"""Type stubs for the native colver extension module."""

from typing import Any

import numpy as np
import numpy.typing as npt

class Env:
    def __init__(self) -> None: ...
    def reset(self) -> tuple[list[float], list[int]]: ...
    def step(self, action: int) -> tuple[list[float], float, bool, list[int]]: ...
    def current_player(self) -> int: ...
    def phase(self) -> int: ...
    def is_terminal(self) -> bool: ...
    def legal_actions(self) -> list[int]: ...
    def legal_actions_reduced(self) -> list[int]: ...
    def legal_action_mask(self) -> npt.NDArray[np.float32]: ...
    def rewards(self) -> tuple[float, float]: ...
    def bid_improved(self) -> int: ...
    def bid_improved_v2(self) -> int: ...
    def bid_improved_v1(self) -> int: ...
    def bid_roro(self) -> int: ...
    def bid_petit_bide(self) -> int: ...
    def bid_moelleux(self) -> int: ...
    def bid_maxi(self) -> int: ...
    def bid_a_dd(self) -> int: ...
    def action_maxi_play(self) -> int: ...
    def deal_outcome(self) -> tuple[float, float]: ...
    def action_naive_ismcts(self, time_ms: int) -> int: ...
    def smart_ismcts_init(self) -> None: ...
    def smart_ismcts_step(self, action: int) -> tuple[list[float], float, bool, list[int]]: ...
    def action_smart_ismcts(self, time_ms: int) -> int: ...
    def rollout(self, n: int) -> tuple[float, float]: ...
    def get_state_bytes(self) -> npt.NDArray[np.uint8]: ...
    def set_state_bytes(self, bytes: list[int]) -> None: ...
    def get_hands(self) -> list[list[int]]: ...
    def get_contract(self) -> dict[str, int]: ...
    def get_current_trick(self) -> list[int]: ...
    def get_played_cards(self) -> list[int]: ...
    def get_points(self) -> tuple[int, int]: ...
    def get_tricks_won(self) -> tuple[int, int]: ...
    def get_belote(self) -> tuple[int, int]: ...
    def get_dealer(self) -> int: ...
    def get_trick_lead(self) -> int: ...
    def set_contract(self, trump: int, value: int, team: int, coinche: int) -> None: ...
    def set_phase_playing(self) -> None: ...
    def get_bid_history(self) -> list[tuple[int, int]]: ...
    def action_naive_ismcts_with_stats(self, time_ms: int) -> dict[str, Any]: ...
    def action_smart_ismcts_with_stats(self, time_ms: int) -> dict[str, Any]: ...
    def evaluate_hand(self, player: int) -> dict[str, Any]: ...
    def action_heuristic_play(self) -> int: ...
    def action_random(self) -> int: ...
    def action_oracle_mcts(self, time_ms: int) -> int: ...
    def dede_init(self) -> None: ...
    def dede_step(self, action: int) -> tuple[list[float], float, bool, list[int]]: ...
    def action_dede(self, time_ms: int) -> int: ...
    def action_dede_with_stats(self, time_ms: int) -> dict[str, Any]: ...
    def action_oracle_dd(self) -> int: ...
    def solve_scores(self) -> dict[str, Any]: ...
    def get_observation(self) -> list[float]: ...
    def load_dmc_model(self, path: str, hidden: int | None = None) -> None: ...
    def has_dmc_model(self) -> bool: ...
    def action_dmc_with_stats(self) -> dict[str, Any]: ...
    def load_bid_model(self, path: str, hidden: int | None = None) -> None: ...
    def has_bid_model(self) -> bool: ...
    def action_bid_nn(self) -> dict[str, Any]: ...
    def load_belief_net(self, path: str) -> None: ...
    def has_belief_net(self) -> bool: ...
    def get_belief_weights(self, observer: int) -> dict[str, Any]: ...
    def get_bid_observation(self) -> list[float]: ...
    def get_bid_mask(self) -> list[float]: ...
    @staticmethod
    def card_name(card_idx: int) -> str: ...
    @staticmethod
    def action_name(action: int, phase: int) -> str: ...
    def to_cfn(self) -> str: ...
    @staticmethod
    def from_cfn(cfn: str) -> "Env": ...
    @staticmethod
    def deal_with_hands(dealer: int, hands: list[list[int]]) -> "Env": ...
