"""Type stubs for the native colver extension module."""

from typing import Any

import os

import numpy as np
import numpy.typing as npt

# Tout paramètre de chemin accepte `str` comme tout `os.PathLike`,
# donc les `pathlib.Path` rendus par `colver.*_path()` / `download_*`.
StrPath = str | os.PathLike[str]

NUM_HAND_CLASSES: int
NUM_HAND_CLASSES_TRUMP: int

def hand_class_id(cards: list[int]) -> int: ...
def hand_class_id_trump(cards: list[int], trump: int) -> int: ...
def hand_from_class_id(class_id: int) -> list[int]: ...
def hand_from_class_id_trump(class_id: int) -> list[int]: ...
def hand_code(cards: list[int], trump: int, level: str = "full") -> str: ...
def matadors(cards: list[int], trump: int) -> int: ...

class Env:
    def __init__(self) -> None: ...
    def reset(self) -> tuple[list[float], list[int]]: ...
    def step(self, action: int) -> tuple[list[float], float, bool, list[int]]: ...
    def current_player(self) -> int: ...
    def phase(self) -> int: ...
    def is_terminal(self) -> bool: ...
    def legal_actions(self) -> list[int]: ...
    def legal_actions_reduced(self) -> list[int]: ...
    def legal_action_mask(self) -> npt.NDArray[np.float32]: ...
    def rewards(self) -> tuple[float, float]: ...
    def bid_improved(self) -> int: ...
    def bid_improved_v2(self) -> int: ...
    def bid_improved_v1(self) -> int: ...
    def bid_maxi(self) -> int: ...
    def bid_a_dd(self) -> int: ...
    def action_maxi_play(self) -> int: ...
    def deal_outcome(self) -> tuple[float, float]: ...
    def action_naive_ismcts(self, time_ms: int) -> int: ...
    def smart_ismcts_init(self) -> None: ...
    def smart_ismcts_step(self, action: int) -> tuple[list[float], float, bool, list[int]]: ...
    def action_smart_ismcts(self, time_ms: int) -> int: ...
    def rollout(self, n: int) -> tuple[float, float]: ...
    def get_state_bytes(self) -> npt.NDArray[np.uint8]: ...
    def set_state_bytes(self, bytes: list[int]) -> None: ...
    def get_hands(self) -> list[list[int]]: ...
    def get_initial_hands(self) -> list[list[int]]: ...
    def get_play_order(self) -> list[int]: ...
    def get_contract(self) -> dict[str, int]: ...
    def get_current_trick(self) -> list[int]: ...
    def get_played_cards(self) -> list[int]: ...
    def get_points(self) -> tuple[int, int]: ...
    def get_tricks_won(self) -> tuple[int, int]: ...
    def get_belote(self) -> tuple[int, int]: ...
    def get_dealer(self) -> int: ...
    def get_trick_lead(self) -> int: ...
    def set_contract(self, trump: int, value: int, team: int, coinche: int) -> None: ...
    def set_phase_playing(self) -> None: ...
    def get_bid_history(self) -> list[tuple[int, int]]: ...
    def action_naive_ismcts_with_stats(self, time_ms: int) -> dict[str, Any]: ...
    def action_smart_ismcts_with_stats(self, time_ms: int) -> dict[str, Any]: ...
    def evaluate_hand(self, player: int) -> dict[str, Any]: ...
    def action_heuristic_play(self) -> int: ...
    def action_random(self) -> int: ...
    def action_oracle_mcts(self, time_ms: int) -> int: ...
    def action_oracle_dd(self) -> int: ...
    def solve_scores(self) -> dict[str, Any]:
        """{scores, deal_scores, best_card} — points cartes 0-252 et écart de
        score marqué N-S − E-O, depuis un seul solve. Les deux échelles ne se
        soustraient pas : la seconde est en escalier."""
        ...
    def deal_score_step(self) -> int:
        """La marche de l'escalier : `4V` sur un contrat normal, `2(162 + V·mult)`
        sous coinche. Un seuil sur un écart de score de donne s'exprime en
        fraction de ce nombre, jamais en valeur absolue."""
        ...
    def get_observation(self) -> list[float]: ...
    def load_dmc_model(self, path: StrPath, hidden: int | None = None) -> None: ...
    def has_dmc_model(self) -> bool: ...
    def action_dmc_with_stats(self) -> dict[str, Any]: ...
    def load_bid_model(self, path: StrPath, hidden: int | None = None,
                       canonical: bool = False) -> None: ...
    def set_match_scores(self, ns: int, ew: int) -> None: ...
    def has_bid_model(self) -> bool: ...
    def action_bid_nn(self) -> dict[str, Any]: ...
    # `canonical=True` for a net trained on the canonical suit ordering (v7+). It cannot
    # be auto-detected — same file size as a physical net — and getting it wrong yields a
    # legal bid in the wrong suit with no error. Mirrors `canonical = true` under `[bid]`.
    def get_bid_observation(self) -> list[float]: ...
    def get_bid_mask(self) -> list[float]: ...
    @staticmethod
    def card_name(card_idx: int) -> str: ...
    @staticmethod
    def action_name(action: int, phase: int) -> str: ...
    def to_cfn(self) -> str: ...
    @staticmethod
    def from_cfn(cfn: str) -> "Env": ...
    @staticmethod
    def deal(dealer: int | None = None, seed: int | None = None) -> "Env":
        """Deal 8 cards to each seat. `seed` makes it reproducible and seeds the
        env's RNG; `dealer` defaults to random, and seat `(dealer + 1) % 4` speaks
        first."""
    @staticmethod
    def deal_with_hands(dealer: int, hands: list[list[int]]) -> "Env": ...
    def redeal_with_hands(self, dealer: int, hands: list[list[int]]) -> None: ...

class Agent:
    """A seated bot built from a bot spec (the arena's TOML format)."""
    def __init__(self, spec: str, seat: int, seed: int = 0) -> None: ...
    @staticmethod
    def from_file(path: StrPath, seat: int, seed: int = 0) -> "Agent": ...
    @property
    def seat(self) -> int: ...
    @property
    def label(self) -> str: ...
    def set_scores(self, ns: int, ew: int) -> None: ...
    def set_time_ms(self, ms: int) -> None: ...
    def init_deal(self, env: Env) -> None: ...
    def observe(self, env: Env, action: int) -> None: ...
    def decide(self, env: Env) -> dict[str, Any]: ...
    def action(self, env: Env) -> int: ...

class Analyst:
    """Read-only introspection of the playgen world model."""
    def __init__(self, model_path: StrPath, seed: int = 0) -> None: ...
    @staticmethod
    def replay(model_path: StrPath, dealer: int, hands: list[list[int]],
               actions: list[int], observer: int, seed: int = 0) -> "Analyst": ...
    def init_deal(self, env: Env, observer: int) -> None: ...
    def observe(self, env: Env, action: int) -> None: ...
    def marginals(self, env: Env, n_worlds: int = 50,
                  temperature: float = 1.0) -> list[list[float]] | None: ...
    def bid_policy(self, env: Env, temperature: float = 1.0) -> list[float] | None: ...
    def auction_deals(self, env: Env, n_worlds: int,
                      temperature: float = 1.0) -> list[list[list[int]]] | None: ...
    def play_worlds(self, env: Env, n_worlds: int,
                    temperature: float = 1.0) -> list[list[list[int]]] | None: ...

class Beliefs:
    """Card-location beliefs (NN + heuristic) from one observer's seat."""
    @staticmethod
    def replay(dealer: int, hands: list[list[int]], actions: list[int],
               observer: int, belief_model: StrPath | None = None) -> "Beliefs": ...
    def weights(self, env: Env) -> dict[str, list[list[float]] | None]: ...
