#!/usr/bin/env python3
"""Train a value network for Belote Contrée position evaluation.

Reads binary training data generated by `generate_value_data`, trains a small MLP,
and exports weights as raw f32 binary for Rust inference.

Usage:
    python scripts/train_value_net.py --data data/value_train.bin --output models/value_net.bin
    python scripts/train_value_net.py --data data/value_train.bin --output models/value_net.bin --hidden 512
"""
import argparse
import struct
import sys
from pathlib import Path

import numpy as np
import torch
import torch.nn as nn
from torch.utils.data import DataLoader, TensorDataset


FEATURE_DIM = 278


class ValueMLP(nn.Module):
    def __init__(self, input_dim: int = FEATURE_DIM, hidden: int = 256):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(input_dim, hidden),
            nn.ReLU(),
            nn.Linear(hidden, hidden),
            nn.ReLU(),
            nn.Linear(hidden, 1),
            nn.Sigmoid(),
        )

    def forward(self, x):
        return self.net(x).squeeze(-1)


def load_binary_data(path: str) -> tuple[np.ndarray, np.ndarray]:
    """Load binary training data.

    Format: [u32 num_records][u32 feature_dim][records...]
    Each record: FEATURE_DIM * f32 features + 1 * f32 label
    """
    data = Path(path).read_bytes()
    num_records = struct.unpack("<I", data[0:4])[0]
    feature_dim = struct.unpack("<I", data[4:8])[0]
    assert feature_dim == FEATURE_DIM, f"Feature dim mismatch: {feature_dim} != {FEATURE_DIM}"

    record_floats = feature_dim + 1
    expected_bytes = 8 + num_records * record_floats * 4
    assert len(data) == expected_bytes, (
        f"File size mismatch: {len(data)} != {expected_bytes}"
    )

    # Parse all floats at once
    all_floats = np.frombuffer(data[8:], dtype=np.float32)
    all_floats = all_floats.reshape(num_records, record_floats)

    features = all_floats[:, :feature_dim].copy()
    labels = all_floats[:, feature_dim].copy()

    return features, labels


def export_weights(model: ValueMLP, path: str, hidden: int):
    """Export model weights as raw f32 binary.

    Layout: W1 (FEATURE_DIM×H), b1 (H), W2 (H×H), b2 (H), W3 (H×1), b3 (1)
    All row-major, little-endian f32.
    """
    state = model.state_dict()

    # net.0 = Linear(FEATURE_DIM, H), net.2 = Linear(H, H), net.4 = Linear(H, 1)
    w1 = state["net.0.weight"].cpu().numpy()  # (H, FEATURE_DIM)
    b1 = state["net.0.bias"].cpu().numpy()    # (H,)
    w2 = state["net.2.weight"].cpu().numpy()  # (H, H)
    b2 = state["net.2.bias"].cpu().numpy()    # (H,)
    w3 = state["net.4.weight"].cpu().numpy()  # (1, H)
    b3 = state["net.4.bias"].cpu().numpy()    # (1,)

    # Rust expects row-major: W[i * in_dim + j] = weight from input j to output i
    # PyTorch Linear stores as (out_features, in_features), which is already row-major
    all_weights = np.concatenate([
        w1.flatten(),   # FEATURE_DIM × H
        b1.flatten(),   # H
        w2.flatten(),   # H × H
        b2.flatten(),   # H
        w3.flatten(),   # H (squeeze from (1, H))
        b3.flatten(),   # 1
    ])

    expected_count = FEATURE_DIM * hidden + hidden + hidden * hidden + hidden + hidden + 1
    assert len(all_weights) == expected_count, (
        f"Weight count mismatch: {len(all_weights)} != {expected_count}"
    )

    Path(path).parent.mkdir(parents=True, exist_ok=True)
    all_weights.astype(np.float32).tofile(path)
    print(f"Exported {len(all_weights)} weights ({len(all_weights) * 4} bytes) to {path}")


def main():
    parser = argparse.ArgumentParser(description="Train value network for Belote")
    parser.add_argument("--data", required=True, help="Path to binary training data")
    parser.add_argument("--output", required=True, help="Path for exported weight file")
    parser.add_argument("--hidden", type=int, default=256, help="Hidden layer size")
    parser.add_argument("--epochs", type=int, default=100, help="Max training epochs")
    parser.add_argument("--batch-size", type=int, default=4096, help="Batch size")
    parser.add_argument("--lr", type=float, default=1e-3, help="Learning rate")
    parser.add_argument("--weight-decay", type=float, default=1e-4, help="Weight decay")
    parser.add_argument("--patience", type=int, default=10, help="Early stopping patience")
    parser.add_argument("--val-split", type=float, default=0.1, help="Validation split ratio")
    parser.add_argument("--seed", type=int, default=42, help="Random seed")
    args = parser.parse_args()

    torch.manual_seed(args.seed)
    np.random.seed(args.seed)

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"Device: {device}")

    # Load data
    print(f"Loading data from {args.data}...")
    features, labels = load_binary_data(args.data)
    print(f"  Records: {len(features)}, Feature dim: {features.shape[1]}")
    print(f"  Label distribution: {labels.mean():.3f} mean, {labels.std():.3f} std")

    # Train/val split
    n = len(features)
    indices = np.random.permutation(n)
    val_size = int(n * args.val_split)
    val_idx = indices[:val_size]
    train_idx = indices[val_size:]

    train_features = torch.from_numpy(features[train_idx]).to(device)
    train_labels = torch.from_numpy(labels[train_idx]).to(device)
    val_features = torch.from_numpy(features[val_idx]).to(device)
    val_labels = torch.from_numpy(labels[val_idx]).to(device)

    print(f"  Train: {len(train_features)}, Val: {len(val_features)}")

    train_dataset = TensorDataset(train_features, train_labels)
    train_loader = DataLoader(train_dataset, batch_size=args.batch_size, shuffle=True)

    # Model
    model = ValueMLP(input_dim=FEATURE_DIM, hidden=args.hidden).to(device)
    param_count = sum(p.numel() for p in model.parameters())
    print(f"  Model: {FEATURE_DIM} → {args.hidden} → {args.hidden} → 1 ({param_count} params)")

    criterion = nn.BCELoss()
    optimizer = torch.optim.Adam(
        model.parameters(), lr=args.lr, weight_decay=args.weight_decay
    )

    # Training loop
    best_val_loss = float("inf")
    best_epoch = 0
    patience_counter = 0

    for epoch in range(1, args.epochs + 1):
        # Train
        model.train()
        train_loss = 0.0
        train_correct = 0
        train_total = 0

        for batch_x, batch_y in train_loader:
            optimizer.zero_grad()
            pred = model(batch_x)
            loss = criterion(pred, batch_y)
            loss.backward()
            optimizer.step()

            train_loss += loss.item() * len(batch_x)
            pred_class = (pred >= 0.5).float()
            label_class = (batch_y >= 0.5).float()
            train_correct += (pred_class == label_class).sum().item()
            train_total += len(batch_x)

        train_loss /= train_total
        train_acc = train_correct / train_total * 100

        # Validate
        model.eval()
        with torch.no_grad():
            val_pred = model(val_features)
            val_loss = criterion(val_pred, val_labels).item()
            val_pred_class = (val_pred >= 0.5).float()
            val_label_class = (val_labels >= 0.5).float()
            val_acc = (val_pred_class == val_label_class).float().mean().item() * 100

        improved = val_loss < best_val_loss
        if improved:
            best_val_loss = val_loss
            best_epoch = epoch
            patience_counter = 0
            # Save best model
            torch.save(model.state_dict(), args.output + ".pt")
        else:
            patience_counter += 1

        marker = " *" if improved else ""
        print(
            f"  Epoch {epoch:3d}: train_loss={train_loss:.4f} train_acc={train_acc:.1f}% "
            f"val_loss={val_loss:.4f} val_acc={val_acc:.1f}%{marker}"
        )

        if patience_counter >= args.patience:
            print(f"  Early stopping at epoch {epoch} (best: {best_epoch})")
            break

    # Load best model and export
    model.load_state_dict(torch.load(args.output + ".pt", weights_only=True))
    export_weights(model, args.output, args.hidden)

    # Final validation stats
    model.eval()
    with torch.no_grad():
        val_pred = model(val_features)
        val_loss = criterion(val_pred, val_labels).item()
        val_acc = (
            ((val_pred >= 0.5).float() == (val_labels >= 0.5).float())
            .float()
            .mean()
            .item()
            * 100
        )

    print(f"\nBest model (epoch {best_epoch}): val_loss={val_loss:.4f}, val_acc={val_acc:.1f}%")
    print(f"Weights saved to: {args.output}")

    # Clean up checkpoint
    Path(args.output + ".pt").unlink(missing_ok=True)


if __name__ == "__main__":
    main()
