[package]
name = "colver-core"
version = "0.1.0"
edition = "2021"

[features]
default = ["rand"]
rand = ["dep:rand"]

[dependencies]
rand = { version = "0.8", optional = true }

[dev-dependencies]
rand = "0.8"

[[bin]]
name = "bench"
path = "src/tests/bench.rs"

[[bin]]
name = "mcts_demo"
path = "src/tests/mcts_demo.rs"

[[bin]]
name = "ismcts_demo"
path = "src/tests/ismcts_demo.rs"

[[bin]]
name = "smart_ismcts_demo"
path = "src/tests/smart_ismcts_demo.rs"
