#!/usr/bin/env python3
"""
Distill the bid NN V2 into interpretable models.

Trains Decision Tree + XGBoost on the CSV generated by the Rust distill_bid binary,
then extracts human-readable bidding rules for each scenario.

Usage:
    # 1. Generate data (Rust, ~5min for 200k deals × 9 scenarios):
    cargo run -p colver-core --bin distill_bid --release

    # 2. Train interpretable models (Python):
    PYTHONPATH=scripts uv run python scripts/distill_bid.py [data/distill/bid_distill.csv]
"""

import sys
from pathlib import Path

import numpy as np
import pandas as pd
from sklearn.tree import DecisionTreeClassifier, export_text
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, accuracy_score

SUIT_NAMES = ["S", "H", "D", "C"]

BASE_FEATURES = [
    "trump_count", "has_jack", "has_nine", "has_ace", "has_ten",
    "has_king", "has_queen", "trump_points", "trump_score", "has_belote",
    "side_aces", "side_tens", "side_voids", "side_singletons",
    "side_doubletons", "total_aces", "best_side_length",
]

RESPONSE_FEATURES = BASE_FEATURES + [
    "partner_support", "is_partner_suit", "opp_suit_cards", "is_opp_suit",
]


def decode_bid_action(action: int) -> tuple[int, int]:
    """Decode action (1-40) to (value_encoded, suit_idx)."""
    if 37 <= action <= 40:
        return 25, action - 37
    action_0 = action - 1
    return action_0 // 4 + 8, action_0 % 4


def load_data(path: str) -> pd.DataFrame:
    df = pd.read_csv(path)
    print(f"Loaded {len(df)} rows")
    print(f"Scenarios: {sorted(df['scenario'].unique())}")
    return df


def build_deal_df(gdf: pd.DataFrame) -> pd.DataFrame:
    """Build one row per deal using fast vectorized ops.

    Each deal has exactly 4 rows (one per suit). We find the suit with
    highest q_80 and the second-best suit.
    """
    # Sort by (deal_id, q_80 desc) so rank within each group of 4
    gdf_sorted = gdf.sort_values(["deal_id", "q_80"], ascending=[True, False]).reset_index(drop=True)

    # Since each deal has exactly 4 rows, after sorting by q_80 desc,
    # rows 0,4,8,... are best, rows 1,5,9,... are second-best
    n = len(gdf_sorted)
    best_mask = np.zeros(n, dtype=bool)
    second_mask = np.zeros(n, dtype=bool)
    for i in range(0, n, 4):
        best_mask[i] = True
        if i + 1 < n:
            second_mask[i + 1] = True

    best = gdf_sorted[best_mask].copy().reset_index(drop=True)
    second = gdf_sorted[second_mask].reset_index(drop=True)

    best["second_trump_score"] = second["trump_score"].values
    best["second_trump_count"] = second["trump_count"].values
    best["nn_bids"] = ((best["nn_action"] >= 1) & (best["nn_action"] <= 40)).astype(int)
    best["nn_coinche"] = (best["nn_action"] == 41).astype(int)

    return best


def analyze_scenario_group(gdf: pd.DataFrame, group_name: str, title: str, features: list, out):
    """Full analysis for a group of scenarios."""
    if len(gdf) == 0:
        out.write(f"\n{'='*80}\n  {title}\n  (no data)\n{'='*80}\n")
        return

    out.write(f"\n{'='*80}\n")
    out.write(f"  {title}\n")
    out.write(f"  Scenarios: {', '.join(sorted(gdf['scenario'].unique()))}\n")
    out.write(f"  Rows: {len(gdf)} ({len(gdf)//4} suit-evaluations)\n")
    out.write(f"{'='*80}\n\n")

    # --- Per-scenario action distribution ---
    for scen in sorted(gdf["scenario"].unique()):
        sdf = gdf[gdf["scenario"] == scen]
        # One row per deal (take first suit row, they all share nn_action)
        deal_actions = sdf.groupby("deal_id")["nn_action"].first()
        n_deals = len(deal_actions)
        pass_rate = (deal_actions == 0).mean()
        bid_rate = ((deal_actions >= 1) & (deal_actions <= 40)).mean()
        coinche_rate = (deal_actions == 41).mean()
        out.write(f"  {scen}: {n_deals} deals — pass {pass_rate:.1%}, bid {bid_rate:.1%}")
        if coinche_rate > 0.001:
            out.write(f", coinche {coinche_rate:.1%}")

        # Bid level distribution
        bids = deal_actions[(deal_actions >= 1) & (deal_actions <= 40)]
        if len(bids) > 0:
            levels = {}
            for a in bids.values:
                val, _ = decode_bid_action(int(a))
                lbl = f"{val*10}" if val < 25 else "capot"
                levels[lbl] = levels.get(lbl, 0) + 1
            top = sorted(levels.items(), key=lambda x: -x[1])[:5]
            out.write(f"  top: {', '.join(f'{k}={v}' for k,v in top)}")
        out.write("\n")
    out.write("\n")

    # --- Per-suit bid classification ---
    out.write("--- Per-suit bid classification ---\n")
    valid_features = [f for f in features if f in gdf.columns]
    X = gdf[valid_features].values
    y = gdf["nn_bids_this_suit"].values
    bid_rate = y.mean()
    out.write(f"Bid rate (per suit): {bid_rate:.1%}\n")

    if bid_rate < 0.005 or bid_rate > 0.995:
        out.write(f"Skipping ML — too extreme\n\n")
    else:
        X_train, X_test, y_train, y_test = train_test_split(
            X, y, test_size=0.2, random_state=42, stratify=y
        )

        dt = DecisionTreeClassifier(
            max_depth=6, min_samples_leaf=200, class_weight="balanced", random_state=42
        )
        dt.fit(X_train, y_train)
        y_pred = dt.predict(X_test)
        out.write(f"\nDecision Tree (depth=6): accuracy={accuracy_score(y_test, y_pred):.3f}\n")
        out.write(classification_report(y_test, y_pred, target_names=["no_bid", "bid"], digits=3) + "\n")
        out.write(f"Tree:\n{export_text(dt, feature_names=valid_features, max_depth=6)}\n")

        try:
            from xgboost import XGBClassifier
            scale = (y_train == 0).sum() / max((y_train == 1).sum(), 1)
            xgb = XGBClassifier(
                n_estimators=200, max_depth=5, learning_rate=0.1,
                scale_pos_weight=scale, random_state=42, verbosity=0,
            )
            xgb.fit(X_train, y_train)
            y_pred_xgb = xgb.predict(X_test)
            out.write(f"XGBoost: accuracy={accuracy_score(y_test, y_pred_xgb):.3f}\n")
            out.write(classification_report(y_test, y_pred_xgb, target_names=["no_bid", "bid"], digits=3) + "\n")
            importances = sorted(zip(valid_features, xgb.feature_importances_), key=lambda x: -x[1])
            out.write("Feature importance:\n")
            for feat, imp in importances:
                out.write(f"  {feat:<22} {imp:.3f} {'█' * int(imp * 50)}\n")
            out.write("\n")
        except ImportError:
            pass

    # --- Per-deal decision ---
    out.write("--- Per-deal decision (best suit) ---\n")
    deal_df = build_deal_df(gdf)

    bid_rate_d = deal_df["nn_bids"].mean()
    coinche_rate_d = deal_df["nn_coinche"].mean()
    out.write(f"Deals: {len(deal_df)}, bid: {bid_rate_d:.1%}")
    if coinche_rate_d > 0.001:
        out.write(f", coinche: {coinche_rate_d:.1%}")
    out.write("\n")

    feats = [
        "trump_count", "has_jack", "has_nine", "has_ace", "has_ten",
        "has_king", "has_queen", "trump_points", "trump_score", "has_belote",
        "side_aces", "side_tens", "side_voids", "side_singletons",
        "side_doubletons", "total_aces", "best_side_length",
        "second_trump_score", "second_trump_count",
    ]
    if "partner_support" in deal_df.columns:
        feats += ["partner_support", "is_partner_suit", "opp_suit_cards", "is_opp_suit"]

    X = deal_df[feats].values
    y = deal_df["nn_bids"].values

    if bid_rate_d < 0.01 or bid_rate_d > 0.99:
        out.write("Skipping ML — too extreme\n\n")
    else:
        X_train, X_test, y_train, y_test = train_test_split(
            X, y, test_size=0.2, random_state=42, stratify=y
        )

        dt5 = DecisionTreeClassifier(
            max_depth=5, min_samples_leaf=300, class_weight="balanced", random_state=42
        )
        dt5.fit(X_train, y_train)
        y_pred = dt5.predict(X_test)
        out.write(f"\nDecision Tree (depth=5): accuracy={accuracy_score(y_test, y_pred):.3f}\n")
        out.write(classification_report(y_test, y_pred, target_names=["pass", "bid"], digits=3) + "\n")
        out.write(f"HUMAN-USABLE TREE:\n{export_text(dt5, feature_names=feats, max_depth=5)}\n")

        try:
            from xgboost import XGBClassifier
            scale = (y_train == 0).sum() / max((y_train == 1).sum(), 1)
            xgb = XGBClassifier(
                n_estimators=300, max_depth=5, learning_rate=0.1,
                scale_pos_weight=scale, random_state=42, verbosity=0,
            )
            xgb.fit(X_train, y_train)
            y_pred_xgb = xgb.predict(X_test)
            out.write(f"XGBoost: accuracy={accuracy_score(y_test, y_pred_xgb):.3f}\n")
            out.write(classification_report(y_test, y_pred_xgb, target_names=["pass", "bid"], digits=3) + "\n")
            importances = sorted(zip(feats, xgb.feature_importances_), key=lambda x: -x[1])
            out.write("Feature importance:\n")
            for feat, imp in importances:
                out.write(f"  {feat:<22} {imp:.3f} {'█' * int(imp * 50)}\n")
            out.write("\n")
        except ImportError:
            pass

    # --- Statistical extraction ---
    extract_stats(deal_df, group_name, out)


def extract_stats(deal_df: pd.DataFrame, group_name: str, out):
    """Extract bid rate tables by trump characteristics."""
    out.write("\n--- Statistical bid rate tables ---\n")
    out.write(f"\n{'J':>3} {'9':>3} {'#':>3}  {'hands':>7} {'bid%':>7}\n")
    out.write("-" * 35 + "\n")

    for has_j in [1, 0]:
        for has_9 in [1, 0]:
            for count in range(0, 9):
                mask = (
                    (deal_df["has_jack"] == has_j) &
                    (deal_df["has_nine"] == has_9) &
                    (deal_df["trump_count"] == count)
                )
                subset = deal_df[mask]
                if len(subset) < 30:
                    continue
                bid_rate = subset["nn_bids"].mean()
                j_str = "J" if has_j else "-"
                n_str = "9" if has_9 else "-"
                out.write(f" {j_str:>3} {n_str:>3} {count:>3}  {len(subset):>7} {bid_rate:>6.1%}\n")
        out.write("\n")

    # Side aces
    out.write("Side aces (when has J):\n")
    j_df = deal_df[deal_df["has_jack"] == 1]
    for sa in range(4):
        s = j_df[j_df["side_aces"] == sa]
        if len(s) < 20:
            continue
        out.write(f"  {sa} aces: bid {s['nn_bids'].mean():5.1%} ({len(s)})\n")

    out.write("\nSide voids (when has J):\n")
    for sv in range(4):
        s = j_df[j_df["side_voids"] == sv]
        if len(s) < 20:
            continue
        out.write(f"  {sv} voids: bid {s['nn_bids'].mean():5.1%} ({len(s)})\n")

    out.write("\nBid rate by trump_score:\n")
    for lo, hi in [(0, 5), (5, 10), (10, 14), (14, 17), (17, 20), (20, 25), (25, 35)]:
        s = deal_df[(deal_df["trump_score"] >= lo) & (deal_df["trump_score"] < hi)]
        if len(s) < 20:
            continue
        out.write(f"  [{lo:>2}-{hi:>2}): bid {s['nn_bids'].mean():5.1%} ({len(s)})\n")

    # Partner support
    if "partner_support" in deal_df.columns and (deal_df["partner_support"] >= 0).any():
        ps = deal_df[deal_df["partner_support"] >= 0]
        if len(ps) > 0:
            out.write("\nPartner suit support (cards in partner's suit):\n")
            for n in range(6):
                s = ps[ps["partner_support"] == n]
                if len(s) < 20:
                    continue
                out.write(f"  {n} cards: bid {s['nn_bids'].mean():5.1%} ({len(s)})\n")

    # Coinche
    if "nn_coinche" in deal_df.columns and deal_df["nn_coinche"].sum() > 10:
        cdf = deal_df[deal_df["nn_coinche"] == 1]
        out.write(f"\nCoinche: {len(cdf)}/{len(deal_df)} ({len(cdf)/len(deal_df):.1%})\n")
        out.write(f"  Avg trump_score: {cdf['trump_score'].mean():.1f}\n")
        out.write(f"  Avg trump_count: {cdf['trump_count'].mean():.1f}\n")
        out.write(f"  % has J: {cdf['has_jack'].mean():.1%}\n")
        out.write(f"  % has 9: {cdf['has_nine'].mean():.1%}\n")
        if "opp_suit_cards" in cdf.columns:
            oc = cdf[cdf["opp_suit_cards"] >= 0]
            if len(oc) > 0:
                out.write(f"  Avg cards in opp suit: {oc['opp_suit_cards'].mean():.1f}\n")

    out.write("\n")


def main():
    csv_path = sys.argv[1] if len(sys.argv) > 1 else "data/distill/bid_distill.csv"

    if not Path(csv_path).exists():
        print(f"Error: {csv_path} not found.")
        print("Generate: cargo run -p colver-core --bin distill_bid --release")
        sys.exit(1)

    df = load_data(csv_path)

    log_path = "data/distill/bid_distill_analysis.log"

    class TeeWriter:
        def __init__(self, *writers):
            self.writers = writers
        def write(self, s):
            for w in self.writers:
                w.write(s)
        def flush(self):
            for w in self.writers:
                w.flush()

    log_file = open(log_path, "w")
    out = TeeWriter(sys.stdout, log_file)

    # Define groups
    groups = [
        ("opening", "POSITION 1: Opening Bid",
         ["pos1_open"], BASE_FEATURES),
        ("passes", "POSITIONS 2-4: After All Passes",
         ["pos2_after_pass", "pos3_after_2p", "pos4_after_3p"], BASE_FEATURES),
        ("partner80", "RESPONSE: Partner Bid 80",
         [f"pos3_partner80_{s}" for s in "shdc"] + [f"pos4_partner80_{s}" for s in "shdc"],
         RESPONSE_FEATURES),
        ("opp80", "DEFENSE: Opponent Bid 80",
         [f"pos2_opp80_{s}" for s in "shdc"] + [f"pos3_opp80_{s}" for s in "shdc"] +
         [f"pos4_opp80_{s}" for s in "shdc"],
         RESPONSE_FEATURES),
    ]

    # Also do each position individually for after-passes
    groups += [
        ("pos2_pass", "POSITION 2: After 1 Pass",
         ["pos2_after_pass"], BASE_FEATURES),
        ("pos3_pass", "POSITION 3: After 2 Passes",
         ["pos3_after_2p"], BASE_FEATURES),
        ("pos4_pass", "POSITION 4: After 3 Passes (Last Chance)",
         ["pos4_after_3p"], BASE_FEATURES),
    ]

    for gname, title, scens, feats in groups:
        mask = df["scenario"].isin(scens)
        gdf = df[mask]
        out.write(f"\n[Processing {gname}: {len(gdf)} rows...]\n")
        out.flush()
        analyze_scenario_group(gdf, gname, title, feats, out)

    out.write(f"\n{'='*80}\n  Full log: {log_path}\n{'='*80}\n")
    log_file.close()
    print(f"\nDone! Log saved to {log_path}")


if __name__ == "__main__":
    main()
