"""Bumblebid self-play training: DQN with DD rewards on full auction trajectories.

Pre-tokenized hands loaded from COLVBB01 pool (generated by gen_bumblebid_pool).
Pool tokens + replay buffer on GPU. Env logic vectorized with numpy.

Usage:
    cargo run -p colver-core --bin gen_bumblebid_pool --release
    PYTHONUNBUFFERED=1 PYTHONPATH=scripts uv run python -m bumblebid.train \
        --pool-file data/pools/bumblebid_2.5M.bin
"""

import argparse
import time
from pathlib import Path

import numpy as np
import torch
import torch.nn.functional as F

try:
    from .model import Bumblebid, NUM_BID_ACTIONS, MAX_SEQ_LEN
    from .data import (
        load_bumblebid_pool, load_dd_pool, BiddingEnv,
        compute_deal_score,
        ACTION_PRIMARY_LUT, ACTION_SUIT_LUT, ACTION_SUIT2_LUT,
        decode_bid,
        SUIT_PERM_T, ACTION_PERM_TABLE,
    )
    from .model import P_NONE, S_NULL, P_CLS, P_POS0, P_RANK0
    from .opponent import BidNetV2, build_bid_obs_batch
except ImportError:
    from model import Bumblebid, NUM_BID_ACTIONS, MAX_SEQ_LEN
    from data import (
        load_bumblebid_pool, load_dd_pool, BiddingEnv,
        compute_deal_score,
        ACTION_PRIMARY_LUT, ACTION_SUIT_LUT, ACTION_SUIT2_LUT,
        decode_bid,
        SUIT_PERM_T, ACTION_PERM_TABLE,
    )
    from model import P_NONE, S_NULL, P_CLS, P_POS0, P_RANK0
    from opponent import BidNetV2, build_bid_obs_batch

BID_PASS = 0
BID_COINCHE = 41
BID_SURCOINCHE = 42

# Bid value/suit lookup for legal mask computation
_BID_VAL_LUT = np.zeros(41, dtype=np.int32)
_BID_SUIT_LUT = np.zeros(41, dtype=np.int32)
for _a in range(1, 41):
    if _a <= 36:
        _BID_VAL_LUT[_a] = (_a - 1) // 4 + 8
        _BID_SUIT_LUT[_a] = (_a - 1) % 4
    else:
        _BID_VAL_LUT[_a] = 25
        _BID_SUIT_LUT[_a] = _a - 37


# ---------------------------------------------------------------------------
# GPU replay buffer
# ---------------------------------------------------------------------------
class GPUReplayBuffer:
    """Circular replay buffer living entirely on GPU."""

    def __init__(self, capacity, device):
        self.capacity = capacity
        self.device = device
        self.primary = torch.zeros(capacity, MAX_SEQ_LEN, dtype=torch.long, device=device)
        self.suits = torch.zeros(capacity, MAX_SEQ_LEN, dtype=torch.long, device=device)
        self.seq_lens = torch.zeros(capacity, dtype=torch.long, device=device)
        self.masks = torch.zeros(capacity, NUM_BID_ACTIONS, dtype=torch.float32, device=device)
        self.actions = torch.zeros(capacity, dtype=torch.long, device=device)
        self.rewards = torch.zeros(capacity, dtype=torch.float32, device=device)
        self.size = 0
        self.pos = 0

    def sample(self, batch_size):
        """Sample a random batch — already on GPU, no transfer needed."""
        idx = torch.randint(self.size, (batch_size,), device=self.device)
        max_len = self.seq_lens[idx].max().item()
        return {
            "primary": self.primary[idx, :max_len],
            "suits": self.suits[idx, :max_len],
            "seq_lens": self.seq_lens[idx],
            "masks": self.masks[idx],
            "actions": self.actions[idx],
            "rewards": self.rewards[idx],
        }


# ---------------------------------------------------------------------------
# Vectorized bidding environment
# ---------------------------------------------------------------------------
MAX_EP_STEPS = 48  # max transitions per auction (40 bids + passes + coinche)


class VecBiddingEnv:
    """Fully vectorized N-env bidding environment.

    Pool tokens on GPU, env state + episode buffers in numpy (vectorized).
    Replay buffer on GPU — flush writes directly to device.
    """

    def __init__(self, n_envs, pool_dealers, pool_primary, pool_suits, pool_dd,
                 device, seed=42, pool_hands=None, opponent=None,
                 pool_real=None, reward_mix=1.0, nn_team_only=False):
        self.n = n_envs
        self.pool_dealers = pool_dealers
        self.pool_dd = pool_dd
        self.pool_real = pool_real  # [N_pool, 4] uint8 or None
        self.reward_mix = reward_mix  # 1.0=DD, 0.0=real, 0.5=blend
        self.nn_team_only = nn_team_only  # if True, only store NN team (NS=0) in replay
        self.n_pool = len(pool_dealers)
        self.rng = np.random.default_rng(seed)
        self.device = device

        # Opponent model (bid_v2) — None means pure self-play
        self.opponent = opponent
        self.pool_hands = pool_hands  # [N_pool, 4] uint32, needed for opponent obs

        # Pre-tokenized hands on GPU: [N_pool, 4, 10]
        self.gpu_primary = torch.from_numpy(pool_primary.astype(np.int64)).to(device)
        self.gpu_suits = torch.from_numpy(pool_suits.astype(np.int64)).to(device)
        # CPU copy for replay buffer (avoid GPU→CPU per transition)
        self.cpu_primary = torch.from_numpy(pool_primary.astype(np.int64))
        self.cpu_suits = torch.from_numpy(pool_suits.astype(np.int64))

        # Per-env state (numpy, vectorized)
        self.deal_idx = np.zeros(n_envs, dtype=np.int64)
        self.env_dealer = np.zeros(n_envs, dtype=np.int32)
        self.env_dd = np.zeros((n_envs, 4), dtype=np.uint8)
        self.env_cur_player = np.zeros(n_envs, dtype=np.int32)
        self.env_consec_passes = np.zeros(n_envs, dtype=np.int32)
        self.env_bid_val = np.full(n_envs, -1, dtype=np.int32)
        self.env_bid_suit = np.zeros(n_envs, dtype=np.int32)
        self.env_bid_team = np.zeros(n_envs, dtype=np.int32)
        self.env_coinche = np.zeros(n_envs, dtype=np.int32)
        self.env_done = np.zeros(n_envs, dtype=bool)

        # Bid tokens (numpy, transferred to GPU in get_batch)
        self.bid_primary = np.zeros((n_envs, 24), dtype=np.int64)
        self.bid_suits = np.zeros((n_envs, 24), dtype=np.int64)
        self.n_bid_tokens = np.zeros(n_envs, dtype=np.int32)

        # Bid history as (seat, action) pairs — needed for opponent obs
        self.bid_history_seats = np.zeros((n_envs, MAX_EP_STEPS), dtype=np.int32)
        self.bid_history_actions = np.zeros((n_envs, MAX_EP_STEPS), dtype=np.int32)
        self.bid_history_len = np.zeros(n_envs, dtype=np.int32)

        # Pre-allocated episode buffers (numpy, vectorized writes)
        self.ep_seats = np.zeros((n_envs, MAX_EP_STEPS), dtype=np.int32)
        self.ep_nb = np.zeros((n_envs, MAX_EP_STEPS), dtype=np.int32)
        self.ep_actions = np.zeros((n_envs, MAX_EP_STEPS), dtype=np.int32)
        self.ep_teams = np.zeros((n_envs, MAX_EP_STEPS), dtype=np.int32)
        self.ep_masks = np.zeros((n_envs, MAX_EP_STEPS, NUM_BID_ACTIONS), dtype=np.float32)
        self.ep_len = np.zeros(n_envs, dtype=np.int32)

        self.reset_all()

    def reset_envs(self, indices):
        idx = np.asarray(indices)
        if len(idx) == 0:
            return
        di = self.rng.integers(self.n_pool, size=len(idx))

        self.deal_idx[idx] = di
        self.env_dealer[idx] = self.pool_dealers[di]
        self.env_dd[idx] = self.pool_dd[di]
        self.env_cur_player[idx] = (self.pool_dealers[di] + 1) % 4
        self.env_consec_passes[idx] = 0
        self.env_bid_val[idx] = -1
        self.env_bid_suit[idx] = 0
        self.env_bid_team[idx] = 0
        self.env_coinche[idx] = 0
        self.env_done[idx] = False
        self.bid_primary[idx] = 0
        self.bid_suits[idx] = 0
        self.n_bid_tokens[idx] = 0
        self.bid_history_len[idx] = 0
        self.ep_len[idx] = 0

    def reset_all(self):
        self.reset_envs(np.arange(self.n))

    # Fixed bucket sizes for CUDA graph compatibility (avoid dynamic shapes)
    _SEQ_BUCKETS = [10, 16, 24, 34]

    def get_batch(self):
        """Build GPU batch. Returns (primary, suits, pad_mask) on device."""
        max_nb = int(self.n_bid_tokens.max())
        raw_len = 10 + max_nb

        # Pad to next bucket for CUDA graph reuse
        seq_len = raw_len
        for b in self._SEQ_BUCKETS:
            if b >= raw_len:
                seq_len = b
                break

        # Hand tokens from GPU pool: [N, 10]
        deal_t = torch.from_numpy(self.deal_idx).to(self.device)
        seat_t = torch.from_numpy(self.env_cur_player.astype(np.int64)).to(self.device)
        hand_p = self.gpu_primary[deal_t, seat_t]
        hand_s = self.gpu_suits[deal_t, seat_t]

        if seq_len == 10:
            pad = torch.zeros(self.n, 10, dtype=torch.bool, device=self.device)
            return hand_p, hand_s, pad

        # Bid tokens: numpy → GPU
        bid_p = torch.from_numpy(self.bid_primary[:, :max_nb].copy()).to(self.device)
        bid_s = torch.from_numpy(self.bid_suits[:, :max_nb].copy()).to(self.device)

        # Pad to bucket size
        pad_cols = seq_len - 10 - max_nb
        if pad_cols > 0:
            z = torch.zeros(self.n, pad_cols, dtype=torch.long, device=self.device)
            batch_p = torch.cat([hand_p, bid_p, z], dim=1)
            batch_s = torch.cat([hand_s, bid_s, z], dim=1)
        else:
            batch_p = torch.cat([hand_p, bid_p], dim=1)
            batch_s = torch.cat([hand_s, bid_s], dim=1)

        lens = torch.from_numpy((10 + self.n_bid_tokens).astype(np.int64)).to(self.device)
        positions = torch.arange(seq_len, device=self.device).unsqueeze(0)
        pad_mask = positions >= lens.unsqueeze(1)

        return batch_p, batch_s, pad_mask

    def compute_legal_masks(self):
        """Vectorized legal masks. Returns [N, 43] float32 numpy."""
        N = self.n
        masks = np.zeros((N, NUM_BID_ACTIONS), dtype=np.float32)
        masks[:, BID_PASS] = 1.0

        no_bid = (self.env_bid_val < 0) & ~self.env_done
        masks[no_bid, 1:41] = 1.0

        has_bid = (self.env_bid_val >= 0) & ~self.env_done
        not_coinched = (self.env_coinche == 0) & has_bid
        if np.any(not_coinched):
            nc = np.where(not_coinched)[0]
            cv, cs, ct = self.env_bid_val[nc], self.env_bid_suit[nc], self.env_bid_team[nc]
            bv = _BID_VAL_LUT[1:41]
            higher = bv[None, :] > cv[:, None]
            masks[nc[:, None], np.arange(1, 41)[None, :]] = higher.astype(np.float32)
            opp = (self.env_cur_player[nc] % 2) != ct
            masks[nc[opp], BID_COINCHE] = 1.0

        coinched = (self.env_coinche == 1) & has_bid
        if np.any(coinched):
            ci = np.where(coinched)[0]
            same = (self.env_cur_player[ci] % 2) == self.env_bid_team[ci]
            masks[ci[same], BID_SURCOINCHE] = 1.0

        return masks

    @torch.no_grad()
    def get_opponent_actions(self, masks_np):
        """Compute actions for EW seats using the opponent model.
        Returns [N] actions (only meaningful where cur_player is EW).
        """
        if self.opponent is None or self.pool_hands is None:
            return None

        is_ew = (self.env_cur_player % 2 == 1) & ~self.env_done
        if not np.any(is_ew):
            return None

        ew_idx = np.where(is_ew)[0]

        # Build bid history lists for opponent obs
        histories = []
        for i in ew_idx:
            bhl = int(self.bid_history_len[i])
            h = list(zip(
                self.bid_history_seats[i, :bhl].tolist(),
                self.bid_history_actions[i, :bhl].tolist(),
            ))
            histories.append(h)

        # Build obs
        di = self.deal_idx[ew_idx]
        obs = build_bid_obs_batch(
            self.pool_hands[di],
            self.env_cur_player[ew_idx],
            self.env_dealer[ew_idx],
            histories,
            self.n_bid_tokens[ew_idx],
        )
        obs_t = torch.from_numpy(obs).to(self.device)
        mask_t = torch.from_numpy(masks_np[ew_idx]).to(self.device)

        with torch.amp.autocast("cuda", dtype=torch.bfloat16):
            q = self.opponent(obs_t)
        q = q.float().masked_fill(mask_t == 0, -1e9)
        opp_actions = q.argmax(dim=-1).cpu().numpy()

        # Build full action array
        result = np.zeros(self.n, dtype=np.int32)
        result[ew_idx] = opp_actions
        return result, is_ew

    def step_all(self, actions, masks_np, replay_buffer):
        """Step all envs. Returns number of completed episodes."""
        # --- Vectorized snapshot (all active seats, both teams) ---
        active = ~self.env_done
        active_idx = np.where(active)[0]
        if len(active_idx) > 0:
            el = self.ep_len[active_idx]
            self.ep_seats[active_idx, el] = self.env_cur_player[active_idx]
            self.ep_nb[active_idx, el] = self.n_bid_tokens[active_idx]
            self.ep_actions[active_idx, el] = actions[active_idx]
            self.ep_teams[active_idx, el] = self.env_cur_player[active_idx] % 2
            self.ep_masks[active_idx, el] = masks_np[active_idx]
            self.ep_len[active_idx] += 1

        # --- Vectorized state update ---
        act = actions
        nb = self.n_bid_tokens.copy()
        can_append = active & (nb + 2 <= 24)
        if np.any(can_append):
            ca = np.where(can_append)[0]
            nbs = nb[ca]
            acts = act[ca]
            self.bid_primary[ca, nbs] = ACTION_PRIMARY_LUT[acts]
            self.bid_suits[ca, nbs] = ACTION_SUIT_LUT[acts]
            self.bid_primary[ca, nbs + 1] = P_NONE
            self.bid_suits[ca, nbs + 1] = ACTION_SUIT2_LUT[acts]
            self.n_bid_tokens[ca] = nbs + 2

        # Record bid history (for opponent obs)
        active_idx = np.where(active)[0]
        bhl = self.bid_history_len[active_idx]
        valid = bhl < MAX_EP_STEPS
        vi = active_idx[valid]
        vl = bhl[valid]
        self.bid_history_seats[vi, vl] = self.env_cur_player[vi]
        self.bid_history_actions[vi, vl] = act[vi]
        self.bid_history_len[vi] = vl + 1

        is_pass = (act == BID_PASS) & active
        self.env_consec_passes[is_pass] += 1

        is_coinche = (act == BID_COINCHE) & active
        self.env_coinche[is_coinche] = 1
        self.env_consec_passes[is_coinche] = 0

        is_surcoinche = (act == BID_SURCOINCHE) & active
        self.env_coinche[is_surcoinche] = 2
        self.env_consec_passes[is_surcoinche] = 0
        self.env_done[is_surcoinche] = True

        is_bid = active & (act >= 1) & (act <= 40)
        if np.any(is_bid):
            bi = np.where(is_bid)[0]
            ba = act[bi]
            self.env_bid_val[bi] = _BID_VAL_LUT[ba]
            self.env_bid_suit[bi] = _BID_SUIT_LUT[ba]
            self.env_bid_team[bi] = self.env_cur_player[bi] % 2
            self.env_coinche[bi] = 0
            self.env_consec_passes[bi] = 0

        still_active = active & ~is_surcoinche
        void_end = still_active & (self.env_bid_val < 0) & (self.env_consec_passes >= 4)
        bid_end = still_active & (self.env_bid_val >= 0) & (self.env_consec_passes >= 3)
        self.env_done[void_end | bid_end] = True

        self.env_cur_player[active] = (self.env_cur_player[active] + 1) % 4

        # --- Flush completed episodes to GPU replay buffer ---
        just_done = np.where(self.env_done & active)[0]
        completed = len(just_done)

        if completed > 0:
            self._flush_episodes(just_done, replay_buffer)
            self.reset_envs(just_done)

        return completed

    def _flush_episodes(self, done_idx, rb):
        """Write completed episodes to GPU replay buffer — fully vectorized."""
        n_done = len(done_idx)
        ep_lens = self.ep_len[done_idx]
        total = int(ep_lens.sum())
        if total == 0:
            return

        # Flat indices: env_flat[t] = which env, step_flat[t] = which step
        env_flat = np.repeat(done_idx, ep_lens)
        step_flat = np.concatenate([np.arange(l) for l in ep_lens])

        # Gather episode buffer data (all numpy, no loops)
        seats = self.ep_seats[env_flat, step_flat]       # [total]
        nbs = self.ep_nb[env_flat, step_flat]             # [total]
        acts = self.ep_actions[env_flat, step_flat]        # [total]
        teams = self.ep_teams[env_flat, step_flat]         # [total]
        masks = self.ep_masks[env_flat, step_flat]         # [total, 43]
        dis = self.deal_idx[env_flat]                      # [total]

        # Compute rewards per done env — blend DD and real points
        ns_rewards = np.zeros(n_done, dtype=np.float32)
        for k, i in enumerate(done_idx):
            if self.env_bid_val[i] >= 0:
                cv = int(self.env_bid_val[i]) * 10
                suit = int(self.env_bid_suit[i])
                team = int(self.env_bid_team[i])
                ns_dd, ew_dd = compute_deal_score(self.env_dd[i], cv, suit, team)
                if self.pool_real is not None and self.reward_mix < 1.0:
                    di = int(self.deal_idx[i])
                    real_dd = self.pool_real[di].copy()
                    ns_real, ew_real = compute_deal_score(real_dd, cv, suit, team)
                    m = self.reward_mix
                    ns_rewards[k] = (m * (ns_dd - ew_dd) + (1 - m) * (ns_real - ew_real)) / 500.0
                else:
                    ns_rewards[k] = (ns_dd - ew_dd) / 500.0

        # Map: env_flat → done_idx position
        done_k = np.repeat(np.arange(n_done), ep_lens)
        rewards_flat = np.where(teams == 0, ns_rewards[done_k], -ns_rewards[done_k])

        # Filter to NN team only (NS=0) when using opponent
        if self.nn_team_only:
            keep = teams == 0
            if not np.any(keep):
                return
            env_flat = env_flat[keep]
            step_flat = step_flat[keep]
            seats = seats[keep]
            nbs = nbs[keep]
            acts = acts[keep]
            teams = teams[keep]
            masks = masks[keep]
            dis = dis[keep]
            rewards_flat = rewards_flat[keep]
            total = int(keep.sum())

        # Build primary/suit sequences (numpy, vectorized)
        pool_p_np = self.cpu_primary.numpy()
        pool_s_np = self.cpu_suits.numpy()

        batch_p = np.zeros((total, MAX_SEQ_LEN), dtype=np.int64)
        batch_s = np.zeros((total, MAX_SEQ_LEN), dtype=np.int64)
        batch_p[:, :10] = pool_p_np[dis, seats]
        batch_s[:, :10] = pool_s_np[dis, seats]

        max_nb = int(nbs.max())
        if max_nb > 0:
            bid_p = self.bid_primary[env_flat, :max_nb]  # [total, max_nb]
            bid_s = self.bid_suits[env_flat, :max_nb]
            bid_mask = np.arange(max_nb)[None, :] < nbs[:, None]
            batch_p[:, 10:10 + max_nb] = bid_p * bid_mask
            batch_s[:, 10:10 + max_nb] = bid_s * bid_mask

        sls = (10 + nbs).astype(np.int64)

        # Single batch transfer to GPU
        all_data = torch.from_numpy(np.column_stack([
            batch_p, batch_s,
            sls[:, None],
            acts[:, None].astype(np.int64),
        ])).to(rb.device, non_blocking=True)
        masks_t = torch.from_numpy(masks).to(rb.device, non_blocking=True)
        rewards_t = torch.from_numpy(rewards_flat).to(rb.device, non_blocking=True)

        bp = all_data[:, :MAX_SEQ_LEN]
        bs = all_data[:, MAX_SEQ_LEN:2 * MAX_SEQ_LEN]
        bsl = all_data[:, 2 * MAX_SEQ_LEN].long()
        ba = all_data[:, 2 * MAX_SEQ_LEN + 1].long()

        # Write to replay buffer (handle wraparound)
        end = rb.pos + total
        if end <= rb.capacity:
            s = slice(rb.pos, end)
            rb.primary[s] = bp
            rb.suits[s] = bs
            rb.seq_lens[s] = bsl
            rb.masks[s] = masks_t
            rb.actions[s] = ba
            rb.rewards[s] = rewards_t
        else:
            first = rb.capacity - rb.pos
            rb.primary[rb.pos:] = bp[:first]
            rb.suits[rb.pos:] = bs[:first]
            rb.seq_lens[rb.pos:] = bsl[:first]
            rb.masks[rb.pos:] = masks_t[:first]
            rb.actions[rb.pos:] = ba[:first]
            rb.rewards[rb.pos:] = rewards_t[:first]
            rem = total - first
            rb.primary[:rem] = bp[first:]
            rb.suits[:rem] = bs[first:]
            rb.seq_lens[:rem] = bsl[first:]
            rb.masks[:rem] = masks_t[first:]
            rb.actions[:rem] = ba[first:]
            rb.rewards[:rem] = rewards_t[first:]
        rb.pos = end % rb.capacity
        rb.size = min(rb.size + total, rb.capacity)


# ---------------------------------------------------------------------------
# Suit augmentation (24x) — apply random suit permutation to training batch
# ---------------------------------------------------------------------------
_SUIT_PERM_GPU = None
_ACTION_PERM_GPU = None


def augment_batch(batch, device):
    """Apply random suit permutation to each sample in batch (in-place)."""
    global _SUIT_PERM_GPU, _ACTION_PERM_GPU
    if _SUIT_PERM_GPU is None:
        _SUIT_PERM_GPU = SUIT_PERM_T.to(device)       # [24, 4]
        _ACTION_PERM_GPU = ACTION_PERM_TABLE.to(device)  # [24, 43]

    B = batch["suits"].shape[0]
    # Pick random permutation per sample
    perm_idx = torch.randint(24, (B,), device=device)

    # Permute suit_ids: map 0-3 through perm, leave 4 (S_NULL) unchanged
    suit_perm = _SUIT_PERM_GPU[perm_idx]  # [B, 4]
    suits = batch["suits"]  # [B, L]
    is_real_suit = suits < 4  # mask for non-NULL suits
    # Gather: for each position, look up suit_perm[b, old_suit]
    permuted = torch.gather(suit_perm, 1, suits.clamp(0, 3))  # [B, L]
    batch["suits"] = torch.where(is_real_suit, permuted, suits)

    # Permute actions
    action_perm = _ACTION_PERM_GPU[perm_idx]  # [B, 43]
    old_actions = batch["actions"]  # [B]
    batch["actions"] = torch.gather(action_perm, 1, old_actions.unsqueeze(1)).squeeze(1)


# ---------------------------------------------------------------------------
# Action selection
# ---------------------------------------------------------------------------
@torch.no_grad()
def select_actions(model, primary, suits, pad_mask, action_mask, eps):
    with torch.amp.autocast("cuda", dtype=torch.bfloat16):
        logits = model(primary, suits, pad_mask)
    logits = logits.float().masked_fill(action_mask == 0, -1e9)
    greedy = logits.argmax(dim=-1).cpu().numpy()
    mask_np = action_mask.cpu().numpy()
    rand_mask = np.random.random(len(greedy)) < eps
    for i in np.where(rand_mask)[0]:
        greedy[i] = np.random.choice(np.where(mask_np[i] > 0)[0])
    return greedy


# ---------------------------------------------------------------------------
# Evaluation: Bumblebid (NS) vs bid_v2 (EW)
# ---------------------------------------------------------------------------
@torch.no_grad()
def evaluate(model, pool_dealers, pool_primary, pool_suits, pool_dd, device,
             n_deals=2000, opponent=None, pool_hands=None, verbose=False):
    """Evaluate Bumblebid (NS) vs opponent (EW). Returns mean NS reward.

    If no opponent, falls back to self-play (all 4 seats = Bumblebid).
    """
    env = BiddingEnv()
    total_reward = 0.0
    rng = np.random.default_rng(99)
    n_void = 0
    n_ns_bid = 0
    n_ew_bid = 0
    ns_contracts = []
    ew_contracts = []

    for _ in range(n_deals):
        idx = rng.integers(len(pool_dealers))
        dealer = int(pool_dealers[idx])
        dd = pool_dd[idx].tolist()

        env.dealer = dealer
        env.dd_pts = dd
        env.bid_history = []
        env.current_player_seat = (dealer + 1) % 4
        env.consecutive_passes = 0
        env.current_bid = None
        env.coinche_level = 0
        env.done = False

        ns_bid_this = False
        ew_bid_this = False

        while not env.done:
            seat = env.current_player_seat
            is_ew = seat % 2 == 1
            mask = env.legal_actions_mask()

            if is_ew and opponent is not None and pool_hands is not None:
                # Opponent (bid_v2) plays for EW
                obs = build_bid_obs_batch(
                    pool_hands[idx:idx+1],
                    np.array([seat]),
                    np.array([dealer]),
                    [env.bid_history],
                    np.array([0]),
                )
                obs_t = torch.from_numpy(obs).to(device)
                m_t = torch.from_numpy(mask).unsqueeze(0).to(device)
                with torch.amp.autocast("cuda", dtype=torch.bfloat16):
                    q = opponent(obs_t)
                q = q.float().masked_fill(m_t == 0, -1e9)
                action = q.argmax(dim=-1).item()
            else:
                # Bumblebid plays for NS (or self-play fallback)
                hp = pool_primary[idx, seat]
                hs = pool_suits[idx, seat]
                primary = list(hp.astype(np.int64))
                suits = list(hs.astype(np.int64))
                for _s, act in env.bid_history:
                    if len(primary) + 2 > MAX_SEQ_LEN:
                        break
                    primary.extend([int(ACTION_PRIMARY_LUT[act]), P_NONE])
                    suits.extend([int(ACTION_SUIT_LUT[act]), int(ACTION_SUIT2_LUT[act])])

                p_t = torch.tensor(primary[:MAX_SEQ_LEN], dtype=torch.long, device=device).unsqueeze(0)
                s_t = torch.tensor(suits[:MAX_SEQ_LEN], dtype=torch.long, device=device).unsqueeze(0)
                m_t = torch.from_numpy(mask).unsqueeze(0).to(device)
                with torch.amp.autocast("cuda", dtype=torch.bfloat16):
                    logits = model(p_t, s_t)
                logits = logits.float().masked_fill(m_t == 0, -1e9)
                action = logits.argmax(dim=-1).item()

            # Track who bid
            if action >= 1 and action <= 40:
                if is_ew:
                    ew_bid_this = True
                else:
                    ns_bid_this = True

            env.step(action)

        if env.current_bid is None:
            n_void += 1
        else:
            val_enc, suit, taker_team = env.current_bid
            if taker_team == 0:
                ns_contracts.append(val_enc * 10)
            else:
                ew_contracts.append(val_enc * 10)
        if ns_bid_this:
            n_ns_bid += 1
        if ew_bid_this:
            n_ew_bid += 1

        ns_r, _ = env.compute_reward()
        total_reward += ns_r

    mean_r = total_reward / n_deals
    if verbose:
        void_pct = 100.0 * n_void / n_deals
        ns_bid_pct = 100.0 * n_ns_bid / n_deals
        ew_bid_pct = 100.0 * n_ew_bid / n_deals
        ns_take_pct = 100.0 * len(ns_contracts) / n_deals if n_deals > 0 else 0
        ew_take_pct = 100.0 * len(ew_contracts) / n_deals if n_deals > 0 else 0
        ns_mean_cv = np.mean(ns_contracts) if ns_contracts else 0
        ew_mean_cv = np.mean(ew_contracts) if ew_contracts else 0
        print(f"        void={void_pct:.1f}%  NS_bid={ns_bid_pct:.1f}%  EW_bid={ew_bid_pct:.1f}%  "
              f"NS_take={ns_take_pct:.1f}%(avg {ns_mean_cv:.0f})  EW_take={ew_take_pct:.1f}%(avg {ew_mean_cv:.0f})",
              flush=True)
    return mean_r


def _save_model(model, path):
    """Save model state dict, stripping torch.compile prefix if present."""
    sd = model.state_dict()
    sd = {k.replace("_orig_mod.", ""): v for k, v in sd.items()}
    torch.save(sd, path)


# ---------------------------------------------------------------------------
# Arena evaluation: full games (bid + DouDou50 play) via PyO3 Env
# ---------------------------------------------------------------------------
@torch.no_grad()
def arena_evaluate(model, device, bid_model_path, play_model_path, n_matches=100):
    """Run n_matches duplicate matches: Bumblebid vs bid_v2, both using DouDou50.
    Returns (bb_wins, v2_wins, avg_diff).
    """
    try:
        from colver import Env
    except ImportError:
        return None

    bb_total = 0.0
    v2_total = 0.0
    bb_wins = 0
    v2_wins = 0

    for i in range(n_matches):
        # Direction A: BB = NS
        env_a = Env()
        env_a.reset()
        env_a.load_bid_model(bid_model_path, 512)
        env_a.load_dmc_model(play_model_path)
        hands = env_a.get_hands()
        dealer = env_a.get_dealer()

        ns_a, ew_a = _arena_play_game(env_a, model, 0, device)

        # Direction B: BB = EW (same deal)
        env_b = Env.deal_with_hands(dealer, hands)
        env_b.load_bid_model(bid_model_path, 512)
        env_b.load_dmc_model(play_model_path)

        ns_b, ew_b = _arena_play_game(env_b, model, 1, device)

        bb_score = ns_a + ew_b
        v2_score = ew_a + ns_b
        bb_total += bb_score
        v2_total += v2_score
        if bb_score > v2_score:
            bb_wins += 1
        elif v2_score > bb_score:
            v2_wins += 1

    avg_diff = (bb_total - v2_total) / n_matches
    return bb_wins, v2_wins, n_matches, avg_diff


def _arena_play_game(env, model, bb_team, device):
    """Play one full game. bb_team: 0=NS, 1=EW."""
    while env.phase() == 0 and not env.is_terminal():
        seat = env.current_player()
        if seat % 2 == bb_team:
            action = _arena_bb_action(env, model, device)
        else:
            action = env.action_bid_nn()["best_action"]
        env.step(action)
    while not env.is_terminal():
        action = env.action_dmc_with_stats()["best_action"]
        env.step(action)
    return env.rewards()


def _arena_bb_action(env, model, device):
    """Get Bumblebid action from Env state."""
    seat = env.current_player()
    dealer = env.get_dealer()
    hand_cards = env.get_hands()[seat]
    bid_history = env.get_bid_history()

    cards = [(c % 8, c // 8) for c in hand_cards]
    cards.sort(key=lambda c: c[1] * 8 + c[0])

    pos = (seat + 4 - dealer) % 4
    primary = [P_CLS, P_POS0 + pos]
    suits = [S_NULL, S_NULL]
    for rank, suit in cards:
        primary.append(P_RANK0 + rank)
        suits.append(suit)
    for _s, act in bid_history:
        if len(primary) + 2 > MAX_SEQ_LEN:
            break
        primary.extend([int(ACTION_PRIMARY_LUT[act]), P_NONE])
        suits.extend([int(ACTION_SUIT_LUT[act]), int(ACTION_SUIT2_LUT[act])])
    while len(primary) < MAX_SEQ_LEN:
        primary.append(0)
        suits.append(0)

    p_t = torch.tensor(primary[:MAX_SEQ_LEN], dtype=torch.long, device=device).unsqueeze(0)
    s_t = torch.tensor(suits[:MAX_SEQ_LEN], dtype=torch.long, device=device).unsqueeze(0)
    mask = env.legal_action_mask()
    m_t = torch.from_numpy(mask[:43]).unsqueeze(0).to(device)
    with torch.amp.autocast("cuda", dtype=torch.bfloat16):
        logits = model(p_t, s_t)
    logits = logits.float().masked_fill(m_t == 0, -1e9)
    return logits.argmax(dim=-1).item()


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
def main():
    p = argparse.ArgumentParser(description="Train Bumblebid (self-play)")
    p.add_argument("--pool-file", default="data/pools/bumblebid_2.5M.bin")
    p.add_argument("--d-model", type=int, default=256)
    p.add_argument("--n-layers", type=int, default=4)
    p.add_argument("--n-heads", type=int, default=8)
    p.add_argument("--n-envs", type=int, default=512)
    p.add_argument("--steps", type=int, default=2_000_000)
    p.add_argument("--batch-size", type=int, default=1024)
    p.add_argument("--lr", type=float, default=3e-4)
    p.add_argument("--buffer-size", type=int, default=2_000_000)
    p.add_argument("--min-buffer", type=int, default=10_000)
    p.add_argument("--train-freq", type=int, default=4)
    p.add_argument("--eps-start", type=float, default=1.0)
    p.add_argument("--eps-end", type=float, default=0.05)
    p.add_argument("--eps-decay-steps", type=int, default=500_000)
    p.add_argument("--weight-decay", type=float, default=0.01)
    p.add_argument("--eval-freq", type=int, default=50_000)
    p.add_argument("--save-freq", type=int, default=500_000)
    p.add_argument("--save-dir", default="models/bumblebid")
    p.add_argument("--seed", type=int, default=42)
    p.add_argument("--compile", action="store_true", help="torch.compile with CUDA graphs")
    p.add_argument("--opponent", type=str, default=None,
                   help="Path to bid_v2 .bin weights for EW opponent")
    p.add_argument("--opponent-ratio", type=float, default=1.0,
                   help="Fraction of steps using opponent (decays to 0)")
    p.add_argument("--opponent-decay-steps", type=int, default=1_000_000,
                   help="Steps over which opponent ratio decays to 0")
    p.add_argument("--nn-team-only", action="store_true",
                   help="Only store NN team (NS) transitions in replay buffer")
    p.add_argument("--dd-pool", type=str, default="data/pools/dd_2.5M.bin",
                   help="Original DD pool (needed for opponent obs)")
    p.add_argument("--reward-mix", type=float, default=1.0,
                   help="Reward mix: 1.0=100%% DD, 0.0=100%% real, 0.5=50/50")
    p.add_argument("--arena-freq", type=int, default=0,
                   help="Run arena eval every N steps (0=disabled). Needs --arena-bid-model and --arena-play-model")
    p.add_argument("--arena-bid-model", type=str, default="models/bid_v2/bid_nn_final.bin")
    p.add_argument("--arena-play-model", type=str, default="models/dmc_50.bin")
    p.add_argument("--arena-matches", type=int, default=100,
                   help="Number of duplicate matches per arena eval")
    args = p.parse_args()

    torch.manual_seed(args.seed)
    np.random.seed(args.seed)
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    save_dir = Path(args.save_dir)
    save_dir.mkdir(parents=True, exist_ok=True)

    # Performance: TF32 matmuls (free precision is fine for training)
    torch.set_float32_matmul_precision("high")
    torch.backends.cudnn.benchmark = True

    dealers, hand_primary, hand_suits, dd_pts, real_pts = load_bumblebid_pool(args.pool_file)
    gpu_mb = (hand_primary.size + hand_suits.size) * 8 / 1e6
    print(f"Pool: {len(dealers):,} deals, GPU: ~{gpu_mb:.0f} MB", flush=True)

    # Load opponent if specified
    opponent_model = None
    pool_hands = None
    if args.opponent:
        opponent_model = BidNetV2.load_from_bin(args.opponent).to(device)
        opponent_model.eval()
        for p_ in opponent_model.parameters():
            p_.requires_grad_(False)
        print(f"Opponent: {args.opponent} ({sum(p_.numel() for p_ in opponent_model.parameters()):,} params)", flush=True)
        _, pool_hands, _ = load_dd_pool(args.dd_pool)
        print(f"Opponent ratio: {args.opponent_ratio} → 0 over {args.opponent_decay_steps:,} steps", flush=True)

    model = Bumblebid(
        d_model=args.d_model, n_layers=args.n_layers, n_heads=args.n_heads,
    ).to(device)
    n_params = sum(pp.numel() for pp in model.parameters())

    # torch.compile with CUDA graphs for maximum throughput
    if args.compile:
        print("Compiling model (reduce-overhead)...", flush=True)
        model = torch.compile(model, mode="reduce-overhead", fullgraph=True)

    print(f"Bumblebid: {n_params:,} params  d={args.d_model} L={args.n_layers} H={args.n_heads}", flush=True)
    print(f"Envs: {args.n_envs}  Steps: {args.steps:,}  LR: {args.lr}", flush=True)
    print(f"Buffer: {args.buffer_size:,} (GPU)  Batch: {args.batch_size}  Train freq: {args.train_freq}", flush=True)
    print(f"Epsilon: {args.eps_start}->{args.eps_end} over {args.eps_decay_steps:,}", flush=True)
    compile_str = "compile+bf16" if args.compile else "eager"
    print(f"Device: {device}  Mode: {compile_str}", flush=True)

    optimizer = torch.optim.AdamW(
        model.parameters(), lr=args.lr, weight_decay=args.weight_decay,
        betas=(0.9, 0.98), fused=True,
    )

    if real_pts is not None and args.reward_mix < 1.0:
        print(f"Reward mix: {args.reward_mix:.2f} (DD={args.reward_mix:.0%}, real={1-args.reward_mix:.0%})", flush=True)
    else:
        if args.reward_mix < 1.0:
            print("WARNING: --reward-mix < 1.0 but pool has no real_pts, using 100% DD", flush=True)
        args.reward_mix = 1.0

    nn_team_only = args.nn_team_only or (opponent_model is not None)
    if nn_team_only and opponent_model is not None:
        print(f"Replay filter: NN team (NS) only", flush=True)

    vec_env = VecBiddingEnv(
        args.n_envs, dealers, hand_primary, hand_suits, dd_pts, device, seed=args.seed,
        pool_hands=pool_hands, opponent=opponent_model,
        pool_real=real_pts, reward_mix=args.reward_mix, nn_team_only=nn_team_only,
    )
    replay_buffer = GPUReplayBuffer(args.buffer_size, device)

    print(
        f"\n{'Step':>10} | {'Eps':>5} | {'Buffer':>7} | {'Loss':>8} | "
        f"{'Episodes':>8} | {'EvalR':>7} | {'Steps/s':>7}",
        flush=True,
    )
    print("-" * 72, flush=True)

    total_episodes = 0
    total_loss = 0.0
    loss_count = 0
    last_log_step = 0
    last_log_time = time.time()

    for step in range(args.steps):
        eps = args.eps_start + (args.eps_end - args.eps_start) * min(step / args.eps_decay_steps, 1.0)

        # Self-play step
        primary, suits, pad_mask = vec_env.get_batch()
        masks_np = vec_env.compute_legal_masks()
        action_mask = torch.from_numpy(masks_np).to(device)
        actions = select_actions(model, primary, suits, pad_mask, action_mask, eps)

        # Use opponent for EW seats (with curriculum decay)
        if opponent_model is not None:
            opp_ratio = args.opponent_ratio * max(0, 1.0 - step / args.opponent_decay_steps)
            if opp_ratio > 0 and np.random.random() < opp_ratio:
                opp_result = vec_env.get_opponent_actions(masks_np)
                if opp_result is not None:
                    opp_actions, is_ew = opp_result
                    actions[is_ew] = opp_actions[is_ew]

        completed = vec_env.step_all(actions, masks_np, replay_buffer)
        total_episodes += completed

        # Training step
        if replay_buffer.size >= args.min_buffer and step % args.train_freq == 0:
            batch = replay_buffer.sample(args.batch_size)
            augment_batch(batch, device)
            max_len = batch["primary"].shape[1]
            # Pad to bucket for CUDA graph reuse
            for bk in [10, 16, 24, 34]:
                if bk >= max_len:
                    max_len = bk
                    break
            if max_len > batch["primary"].shape[1]:
                pad_cols = max_len - batch["primary"].shape[1]
                z = torch.zeros(args.batch_size, pad_cols, dtype=torch.long, device=device)
                batch["primary"] = torch.cat([batch["primary"], z], dim=1)
                batch["suits"] = torch.cat([batch["suits"], z], dim=1)
            pad_mask_b = torch.arange(max_len, device=device).unsqueeze(0) >= batch["seq_lens"].unsqueeze(1)

            with torch.amp.autocast("cuda", dtype=torch.bfloat16):
                logits = model(batch["primary"], batch["suits"], pad_mask_b)
                q_taken = logits.gather(1, batch["actions"].unsqueeze(1)).squeeze(1)
                loss = F.mse_loss(q_taken, batch["rewards"])

            optimizer.zero_grad(set_to_none=True)
            loss.backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
            optimizer.step()
            total_loss += loss.item()
            loss_count += 1

        # Logging
        if (step + 1) % 10_000 == 0:
            elapsed = time.time() - last_log_time
            sps = (step + 1 - last_log_step) / max(elapsed, 1e-6)
            avg_loss = total_loss / max(loss_count, 1)
            print(
                f"{step+1:10,} | {eps:5.3f} | {replay_buffer.size:7,} | "
                f"{avg_loss:8.5f} | {total_episodes:8,} | {'--':>7} | {sps:7.0f}",
                flush=True,
            )
            total_loss = 0.0
            loss_count = 0
            last_log_step = step + 1
            last_log_time = time.time()

        if (step + 1) % args.eval_freq == 0:
            eval_r = evaluate(
                model, dealers, hand_primary, hand_suits, dd_pts, device,
                opponent=opponent_model, pool_hands=pool_hands, verbose=True,
            )
            label = "vs bid_v2" if opponent_model else "self-play"
            print(f"  >>> Eval ({label}): {eval_r:+.4f}", flush=True)
            _save_model(model, save_dir / "latest.pt")

        if args.arena_freq > 0 and (step + 1) % args.arena_freq == 0:
            result = arena_evaluate(
                model, device, args.arena_bid_model, args.arena_play_model,
                n_matches=args.arena_matches,
            )
            if result is not None:
                bb_w, v2_w, n, diff = result
                print(f"  >>> Arena ({n} matches): BB={bb_w} V2={v2_w} diff={diff:+.1f}", flush=True)

        if (step + 1) % args.save_freq == 0:
            _save_model(model, save_dir / f"step_{step+1}.pt")

    _save_model(model, save_dir / "final.pt")
    print(f"\nDone. Episodes: {total_episodes:,}", flush=True)


if __name__ == "__main__":
    main()
