/// Train the belief network (card location prediction) using supervised learning.
///
/// Loads binary data generated by `generate_belief_data`, splits into train/val,
/// and trains with masked cross-entropy loss.
///
/// Usage:
///   cargo run -p colver-core --bin train_belief_net --features dmc_train --release -- \
///     --data data/belief_train.bin --epochs 20 --batch-size 512 --lr 3e-4 \
///     --val-split 0.05 --output models/belief_net.bin

use std::io::Read;
use std::time::Instant;

use clap::Parser;
use candle_core::Device;
use rand::seq::SliceRandom;
use rand::rngs::StdRng;
use rand::SeedableRng;

use colver_core::belief_candle::BeliefTrainer;
use colver_core::belief_obs::BELIEF_OBS_DIM;

const MAGIC: &[u8; 8] = b"COLVBL01";

#[derive(Parser)]
#[command(name = "train_belief_net")]
struct Args {
    /// Path to training data binary.
    #[arg(long)]
    data: String,

    /// Number of training epochs.
    #[arg(long, default_value = "20")]
    epochs: usize,

    /// Mini-batch size.
    #[arg(long, default_value = "512")]
    batch_size: usize,

    /// Learning rate.
    #[arg(long, default_value = "3e-4")]
    lr: f64,

    /// Hidden layer size.
    #[arg(long, default_value = "512")]
    hidden: usize,

    /// Weight decay.
    #[arg(long, default_value = "1e-4")]
    weight_decay: f64,

    /// Validation split fraction.
    #[arg(long, default_value = "0.05")]
    val_split: f64,

    /// Output path for binary weights.
    #[arg(long, default_value = "models/belief_net.bin")]
    output: String,

    /// Checkpoint directory (safetensors).
    #[arg(long, default_value = "models/belief_checkpoints")]
    checkpoint_dir: String,

    /// Random seed.
    #[arg(long, default_value = "42")]
    seed: u64,
}

/// Loaded dataset.
struct Dataset {
    obs: Vec<f32>,       // num_samples × BELIEF_OBS_DIM
    targets: Vec<u8>,    // num_samples × 32
    masks: Vec<u32>,     // num_samples
    num_samples: usize,
}

impl Dataset {
    fn load(path: &str) -> Self {
        let mut file = std::fs::File::open(path).unwrap_or_else(|e| {
            eprintln!("Failed to open data file {}: {}", path, e);
            std::process::exit(1);
        });

        // Read header
        let mut magic = [0u8; 8];
        file.read_exact(&mut magic).unwrap();
        if &magic != MAGIC {
            eprintln!("Invalid magic bytes in {}", path);
            std::process::exit(1);
        }

        let mut buf4 = [0u8; 4];
        file.read_exact(&mut buf4).unwrap();
        let obs_dim = u32::from_le_bytes(buf4) as usize;
        assert_eq!(obs_dim, BELIEF_OBS_DIM, "obs_dim mismatch: file has {}, expected {}", obs_dim, BELIEF_OBS_DIM);

        let mut buf8 = [0u8; 8];
        file.read_exact(&mut buf8).unwrap();
        let num_samples = u64::from_le_bytes(buf8) as usize;

        println!("Loading {} samples from {}", num_samples, path);

        // Read all samples
        let sample_bytes = BELIEF_OBS_DIM * 4 + 32 + 4; // obs (f32) + target (u8) + mask (u32)
        let mut raw = vec![0u8; num_samples * sample_bytes];
        file.read_exact(&mut raw).unwrap();

        let mut obs = Vec::with_capacity(num_samples * BELIEF_OBS_DIM);
        let mut targets = Vec::with_capacity(num_samples * 32);
        let mut masks = Vec::with_capacity(num_samples);

        for i in 0..num_samples {
            let base = i * sample_bytes;

            // obs: BELIEF_OBS_DIM × f32
            for j in 0..BELIEF_OBS_DIM {
                let off = base + j * 4;
                let f = f32::from_le_bytes([raw[off], raw[off + 1], raw[off + 2], raw[off + 3]]);
                obs.push(f);
            }

            // target: 32 × u8
            let target_off = base + BELIEF_OBS_DIM * 4;
            targets.extend_from_slice(&raw[target_off..target_off + 32]);

            // mask: u32
            let mask_off = target_off + 32;
            let mask = u32::from_le_bytes([
                raw[mask_off], raw[mask_off + 1], raw[mask_off + 2], raw[mask_off + 3],
            ]);
            masks.push(mask);
        }

        Dataset { obs, targets, masks, num_samples }
    }
}

fn main() {
    let args = Args::parse();

    println!("=== Belief Network Training ===");
    println!("Data:        {}", args.data);
    println!("Epochs:      {}", args.epochs);
    println!("Batch size:  {}", args.batch_size);
    println!("Hidden:      {}", args.hidden);
    println!("LR:          {}", args.lr);
    println!("Val split:   {}", args.val_split);
    println!("Output:      {}", args.output);

    // Load data
    let dataset = Dataset::load(&args.data);
    println!("Loaded {} samples", dataset.num_samples);

    // Split into train/val
    let mut rng = StdRng::seed_from_u64(args.seed);
    let mut indices: Vec<usize> = (0..dataset.num_samples).collect();
    indices.shuffle(&mut rng);

    let val_size = (dataset.num_samples as f64 * args.val_split) as usize;
    let train_size = dataset.num_samples - val_size;
    let val_indices = &indices[train_size..];
    let train_indices = &indices[..train_size];

    println!("Train: {} samples, Val: {} samples", train_size, val_size);

    // Detect device
    let device = if candle_core::utils::cuda_is_available() {
        println!("Using CUDA");
        Device::new_cuda(0).unwrap()
    } else {
        println!("Using CPU");
        Device::Cpu
    };

    // Create trainer
    let mut trainer = BeliefTrainer::new(args.hidden, args.lr, args.weight_decay, device).unwrap();

    // Create checkpoint directory
    std::fs::create_dir_all(&args.checkpoint_dir).ok();

    // Pre-extract validation set
    let val_obs = extract_obs(&dataset, val_indices);
    let val_targets = extract_targets(&dataset, val_indices);
    let val_masks = extract_masks(&dataset, val_indices);

    let mut best_val_loss = f32::INFINITY;

    for epoch in 0..args.epochs {
        let epoch_start = Instant::now();

        // Shuffle training indices
        let mut train_idx: Vec<usize> = train_indices.to_vec();
        train_idx.shuffle(&mut rng);

        // Train
        let mut epoch_loss = 0.0f64;
        let mut num_batches = 0;

        for batch_start in (0..train_size).step_by(args.batch_size) {
            let batch_end = (batch_start + args.batch_size).min(train_size);
            let batch_indices = &train_idx[batch_start..batch_end];

            let batch_obs = extract_obs(&dataset, batch_indices);
            let batch_targets = extract_targets(&dataset, batch_indices);
            let batch_masks = extract_masks(&dataset, batch_indices);

            let loss = trainer.train_step(&batch_obs, &batch_targets, &batch_masks).unwrap();
            epoch_loss += loss as f64;
            num_batches += 1;
        }

        let avg_train_loss = epoch_loss / num_batches as f64;

        // Validate (process in chunks to avoid OOM)
        let val_batch = 4096;
        let mut val_loss_sum = 0.0f64;
        let mut val_batches = 0;
        let mut val_correct = 0u64;
        let mut val_total = 0u64;

        for batch_start in (0..val_size).step_by(val_batch) {
            let batch_end = (batch_start + val_batch).min(val_size);
            let bs = batch_end - batch_start;

            let obs_slice = &val_obs[batch_start * BELIEF_OBS_DIM..batch_end * BELIEF_OBS_DIM];
            let targets_slice = &val_targets[batch_start * 32..batch_end * 32];
            let masks_slice = &val_masks[batch_start..batch_end];

            let loss = trainer.eval_loss(obs_slice, targets_slice, masks_slice).unwrap();
            val_loss_sum += loss as f64 * bs as f64;

            let (correct, total) = trainer.eval_accuracy(obs_slice, targets_slice, masks_slice).unwrap();
            val_correct += correct;
            val_total += total;
            val_batches += bs;
        }

        let avg_val_loss = val_loss_sum / val_batches as f64;
        let val_acc = val_correct as f64 / val_total as f64;
        let elapsed = epoch_start.elapsed().as_secs_f64();

        println!(
            "Epoch {:2}/{}: train_loss={:.4} val_loss={:.4} val_acc={:.2}% ({:.1}s)",
            epoch + 1, args.epochs, avg_train_loss, avg_val_loss,
            val_acc * 100.0, elapsed,
        );

        // Save checkpoint
        let ckpt_path = format!("{}/epoch_{}.safetensors", args.checkpoint_dir, epoch + 1);
        trainer.save_checkpoint(&ckpt_path).unwrap();

        // Save best model
        if (avg_val_loss as f32) < best_val_loss {
            best_val_loss = avg_val_loss as f32;
            // Export parent directory
            if let Some(parent) = std::path::Path::new(&args.output).parent() {
                std::fs::create_dir_all(parent).ok();
            }
            trainer.export_binary(&args.output).unwrap();
            println!("  → New best model saved to {} (val_loss={:.4})", args.output, best_val_loss);
        }
    }

    println!("\nTraining complete. Best val_loss={:.4}", best_val_loss);
    println!("Model saved to {}", args.output);
}

fn extract_obs(dataset: &Dataset, indices: &[usize]) -> Vec<f32> {
    let mut result = Vec::with_capacity(indices.len() * BELIEF_OBS_DIM);
    for &idx in indices {
        let start = idx * BELIEF_OBS_DIM;
        result.extend_from_slice(&dataset.obs[start..start + BELIEF_OBS_DIM]);
    }
    result
}

fn extract_targets(dataset: &Dataset, indices: &[usize]) -> Vec<u8> {
    let mut result = Vec::with_capacity(indices.len() * 32);
    for &idx in indices {
        let start = idx * 32;
        result.extend_from_slice(&dataset.targets[start..start + 32]);
    }
    result
}

fn extract_masks(dataset: &Dataset, indices: &[usize]) -> Vec<u32> {
    indices.iter().map(|&idx| dataset.masks[idx]).collect()
}
