/// Train the belief network (card location prediction) using supervised learning.
///
/// Loads binary data generated by `generate_belief_data`, splits into train/val,
/// and trains with masked cross-entropy loss.
///
/// V2 mode (--v2): Uses 414-dim observations with hard constraint mask input.
/// Augmentation (--augment): Applies random suit permutations for 24x data diversity.
///
/// Usage:
///   cargo run -p colver-core --bin train_belief_net --features dmc_train --release -- \
///     --data data/belief_train.bin --epochs 20 --batch-size 512 --lr 3e-4 \
///     --val-split 0.05 --output models/belief_net.bin
///
///   # V2 with augmentation:
///   cargo run -p colver-core --bin train_belief_net --features dmc_train --release -- \
///     --replays data/games_500k.bin --epochs 100 --batch-size 512 --lr 3e-4 \
///     --v2 --augment --cosine-lr --warmup-epochs 5 --output models/belief_net_v2.bin

use std::io::Read;
use std::time::Instant;

use clap::Parser;
use candle_core::Device;
use rand::seq::SliceRandom;
use rand::rngs::StdRng;
use rand::{Rng, SeedableRng};

use colver_core::belief_candle::BeliefTrainer;
use colver_core::belief_obs::{BELIEF_OBS_DIM, BELIEF_OBS_DIM_V2};
use colver_core::game_replay::GameReplay;
use colver_core::suit_perm;

const MAGIC: &[u8; 8] = b"COLVBL01";

#[derive(Parser)]
#[command(name = "train_belief_net")]
struct Args {
    /// Path to training data binary (COLVBL01 format).
    #[arg(long)]
    data: Option<String>,

    /// Path to game replays (COLVGM01 format). Alternative to --data.
    /// Extracts belief samples on startup (~2-5s for 500K games).
    #[arg(long)]
    replays: Option<String>,

    /// Number of training epochs.
    #[arg(long, default_value = "20")]
    epochs: usize,

    /// Mini-batch size.
    #[arg(long, default_value = "512")]
    batch_size: usize,

    /// Learning rate.
    #[arg(long, default_value = "3e-4")]
    lr: f64,

    /// Hidden layer size.
    #[arg(long, default_value = "512")]
    hidden: usize,

    /// Weight decay.
    #[arg(long, default_value = "1e-4")]
    weight_decay: f64,

    /// Validation split fraction.
    #[arg(long, default_value = "0.05")]
    val_split: f64,

    /// Output path for binary weights.
    #[arg(long, default_value = "models/belief_net.bin")]
    output: String,

    /// Checkpoint directory (safetensors).
    #[arg(long, default_value = "models/belief_checkpoints")]
    checkpoint_dir: String,

    /// Random seed.
    #[arg(long, default_value = "42")]
    seed: u64,

    /// Use cosine LR schedule (anneals from lr to min-lr over all epochs).
    #[arg(long, default_value = "false")]
    cosine_lr: bool,

    /// Minimum learning rate for cosine schedule.
    #[arg(long, default_value = "1e-6")]
    min_lr: f64,

    /// Number of linear warmup epochs (ramps from min-lr to lr).
    #[arg(long, default_value = "0")]
    warmup_epochs: usize,

    /// Use V2 observations (414-dim with hard constraint mask input).
    #[arg(long, default_value = "false")]
    v2: bool,

    /// Enable suit permutation augmentation (24x data diversity).
    #[arg(long, default_value = "false")]
    augment: bool,
}

/// Loaded dataset.
struct Dataset {
    obs: Vec<f32>,                     // num_samples × BELIEF_OBS_DIM (always V1 base)
    targets: Vec<u8>,                  // num_samples × 32
    masks: Vec<u32>,                   // num_samples
    hard_constraints: Option<Vec<f32>>, // V2: num_samples × 96 (flat)
    num_samples: usize,
}

impl Dataset {
    fn load(path: &str) -> Self {
        let mut file = std::fs::File::open(path).unwrap_or_else(|e| {
            eprintln!("Failed to open data file {}: {}", path, e);
            std::process::exit(1);
        });

        // Read header
        let mut magic = [0u8; 8];
        file.read_exact(&mut magic).unwrap();
        if &magic != MAGIC {
            eprintln!("Invalid magic bytes in {}", path);
            std::process::exit(1);
        }

        let mut buf4 = [0u8; 4];
        file.read_exact(&mut buf4).unwrap();
        let obs_dim = u32::from_le_bytes(buf4) as usize;
        assert_eq!(obs_dim, BELIEF_OBS_DIM, "obs_dim mismatch: file has {}, expected {}", obs_dim, BELIEF_OBS_DIM);

        let mut buf8 = [0u8; 8];
        file.read_exact(&mut buf8).unwrap();
        let num_samples = u64::from_le_bytes(buf8) as usize;

        println!("Loading {} samples from {}", num_samples, path);

        // Read all samples
        let sample_bytes = BELIEF_OBS_DIM * 4 + 32 + 4; // obs (f32) + target (u8) + mask (u32)
        let mut raw = vec![0u8; num_samples * sample_bytes];
        file.read_exact(&mut raw).unwrap();

        let mut obs = Vec::with_capacity(num_samples * BELIEF_OBS_DIM);
        let mut targets = Vec::with_capacity(num_samples * 32);
        let mut masks = Vec::with_capacity(num_samples);

        for i in 0..num_samples {
            let base = i * sample_bytes;

            // obs: BELIEF_OBS_DIM × f32
            for j in 0..BELIEF_OBS_DIM {
                let off = base + j * 4;
                let f = f32::from_le_bytes([raw[off], raw[off + 1], raw[off + 2], raw[off + 3]]);
                obs.push(f);
            }

            // target: 32 × u8
            let target_off = base + BELIEF_OBS_DIM * 4;
            targets.extend_from_slice(&raw[target_off..target_off + 32]);

            // mask: u32
            let mask_off = target_off + 32;
            let mask = u32::from_le_bytes([
                raw[mask_off], raw[mask_off + 1], raw[mask_off + 2], raw[mask_off + 3],
            ]);
            masks.push(mask);
        }

        Dataset { obs, targets, masks, hard_constraints: None, num_samples }
    }

    fn from_replays(path: &str, v2: bool) -> Self {
        println!("Loading game replays from {}...", path);
        let load_start = Instant::now();
        let replays = GameReplay::load_all(path).unwrap_or_else(|e| {
            eprintln!("Failed to load replays from {}: {}", path, e);
            std::process::exit(1);
        });
        let load_elapsed = load_start.elapsed().as_secs_f64();
        println!("Loaded {} games in {:.2}s", replays.len(), load_elapsed);

        println!("Extracting belief samples{}...", if v2 { " (V2 with hard constraints)" } else { "" });
        let extract_start = Instant::now();

        let samples = if v2 {
            #[cfg(feature = "parallel")]
            { colver_core::game_replay::extract_belief_samples_v2_parallel(&replays) }
            #[cfg(not(feature = "parallel"))]
            { colver_core::game_replay::extract_belief_samples_v2(&replays) }
        } else {
            #[cfg(feature = "parallel")]
            { colver_core::game_replay::extract_belief_samples_parallel(&replays) }
            #[cfg(not(feature = "parallel"))]
            { colver_core::game_replay::extract_belief_samples(&replays) }
        };

        let extract_elapsed = extract_start.elapsed().as_secs_f64();
        let num_samples = samples.len();
        println!(
            "Extracted {} samples in {:.2}s ({:.1} samples/game)",
            num_samples,
            extract_elapsed,
            num_samples as f64 / replays.len().max(1) as f64,
        );

        // Flatten into Dataset format
        let mut obs = Vec::with_capacity(num_samples * BELIEF_OBS_DIM);
        let mut targets = Vec::with_capacity(num_samples * 32);
        let mut masks = Vec::with_capacity(num_samples);
        let mut hard_constraints = if v2 {
            Some(Vec::with_capacity(num_samples * 96))
        } else {
            None
        };

        for sample in samples {
            obs.extend_from_slice(&sample.obs);
            targets.extend_from_slice(&sample.target);
            masks.push(sample.mask);
            if let Some(ref mut hc) = hard_constraints {
                if let Some(ref c) = sample.hard_constraints {
                    hc.extend_from_slice(c);
                }
            }
        }

        Dataset { obs, targets, masks, hard_constraints, num_samples }
    }
}

fn main() {
    let args = Args::parse();

    // Validate: exactly one of --data or --replays must be provided
    if args.data.is_none() && args.replays.is_none() {
        eprintln!("Error: must provide either --data or --replays");
        std::process::exit(1);
    }
    if args.data.is_some() && args.replays.is_some() {
        eprintln!("Error: cannot provide both --data and --replays");
        std::process::exit(1);
    }

    // V2 requires --replays (COLVBL01 doesn't store hard constraints)
    if args.v2 && args.data.is_some() {
        eprintln!("Error: --v2 requires --replays (COLVBL01 format doesn't contain hard constraints)");
        std::process::exit(1);
    }

    let source = if let Some(ref path) = args.data {
        path.clone()
    } else {
        args.replays.as_ref().unwrap().clone()
    };

    let obs_dim = if args.v2 { BELIEF_OBS_DIM_V2 } else { BELIEF_OBS_DIM };

    println!("=== Belief Network Training ===");
    println!("Source:      {}", source);
    println!("Obs dim:     {} ({})", obs_dim, if args.v2 { "V2" } else { "V1" });
    if args.augment {
        println!("Augment:     suit permutation (24x)");
    }
    println!("Epochs:      {}", args.epochs);
    println!("Batch size:  {}", args.batch_size);
    println!("Hidden:      {}", args.hidden);
    println!("LR:          {}", args.lr);
    if args.cosine_lr {
        println!("LR schedule: cosine (min_lr={}, warmup={})", args.min_lr, args.warmup_epochs);
    }
    println!("Val split:   {}", args.val_split);
    println!("Output:      {}", args.output);

    // Load data
    let dataset = if let Some(ref path) = args.data {
        Dataset::load(path)
    } else {
        Dataset::from_replays(args.replays.as_ref().unwrap(), args.v2)
    };
    println!("Loaded {} samples", dataset.num_samples);

    // Split into train/val
    let mut rng = StdRng::seed_from_u64(args.seed);
    let mut indices: Vec<usize> = (0..dataset.num_samples).collect();
    indices.shuffle(&mut rng);

    let val_size = (dataset.num_samples as f64 * args.val_split) as usize;
    let train_size = dataset.num_samples - val_size;
    let val_indices = &indices[train_size..];
    let train_indices = &indices[..train_size];

    println!("Train: {} samples, Val: {} samples", train_size, val_size);

    // Detect device
    let device = if candle_core::utils::cuda_is_available() {
        println!("Using CUDA");
        Device::new_cuda(0).unwrap()
    } else {
        println!("Using CPU");
        Device::Cpu
    };

    // Create trainer with appropriate obs_dim
    let mut trainer = BeliefTrainer::new(obs_dim, args.hidden, args.lr, args.weight_decay, device).unwrap();

    // Create checkpoint directory
    std::fs::create_dir_all(&args.checkpoint_dir).ok();

    // Pre-extract validation set (no augmentation on validation)
    let val_obs = build_obs_batch(&dataset, val_indices, args.v2);
    let val_targets = extract_targets(&dataset, val_indices);
    let val_masks = extract_masks(&dataset, val_indices);

    let mut best_val_loss = f32::INFINITY;

    for epoch in 0..args.epochs {
        let epoch_start = Instant::now();

        // Cosine LR schedule with optional warmup
        if args.cosine_lr {
            let lr = if epoch < args.warmup_epochs {
                let t = (epoch + 1) as f64 / args.warmup_epochs as f64;
                args.min_lr + (args.lr - args.min_lr) * t
            } else {
                let t = (epoch - args.warmup_epochs) as f64
                    / (args.epochs - args.warmup_epochs).max(1) as f64;
                args.min_lr + 0.5 * (args.lr - args.min_lr) * (1.0 + (std::f64::consts::PI * t).cos())
            };
            trainer.set_lr(lr);
        }

        // Shuffle training indices
        let mut train_idx: Vec<usize> = train_indices.to_vec();
        train_idx.shuffle(&mut rng);

        // Train
        let mut epoch_loss = 0.0f64;
        let mut num_batches = 0;

        for batch_start in (0..train_size).step_by(args.batch_size) {
            let batch_end = (batch_start + args.batch_size).min(train_size);
            let batch_indices = &train_idx[batch_start..batch_end];

            // Build batch with optional augmentation
            let (batch_obs, batch_targets, batch_masks) = if args.augment {
                build_augmented_batch(&dataset, batch_indices, args.v2, &mut rng)
            } else {
                let obs = build_obs_batch(&dataset, batch_indices, args.v2);
                let targets = extract_targets(&dataset, batch_indices);
                let masks = extract_masks(&dataset, batch_indices);
                (obs, targets, masks)
            };

            let loss = trainer.train_step(&batch_obs, &batch_targets, &batch_masks).unwrap();
            epoch_loss += loss as f64;
            num_batches += 1;
        }

        let avg_train_loss = epoch_loss / num_batches as f64;

        // Validate (process in chunks to avoid OOM)
        let val_batch = 4096;
        let mut val_loss_sum = 0.0f64;
        let mut val_batches = 0;
        let mut val_correct = 0u64;
        let mut val_total = 0u64;

        for batch_start in (0..val_size).step_by(val_batch) {
            let batch_end = (batch_start + val_batch).min(val_size);
            let bs = batch_end - batch_start;

            let obs_slice = &val_obs[batch_start * obs_dim..batch_end * obs_dim];
            let targets_slice = &val_targets[batch_start * 32..batch_end * 32];
            let masks_slice = &val_masks[batch_start..batch_end];

            let loss = trainer.eval_loss(obs_slice, targets_slice, masks_slice).unwrap();
            val_loss_sum += loss as f64 * bs as f64;

            let (correct, total) = trainer.eval_accuracy(obs_slice, targets_slice, masks_slice).unwrap();
            val_correct += correct;
            val_total += total;
            val_batches += bs;
        }

        let avg_val_loss = val_loss_sum / val_batches as f64;
        let val_acc = val_correct as f64 / val_total as f64;
        let elapsed = epoch_start.elapsed().as_secs_f64();

        if args.cosine_lr {
            let lr = trainer.current_lr();
            println!(
                "Epoch {:3}/{}: train_loss={:.4} val_loss={:.4} val_acc={:.2}% lr={:.2e} ({:.1}s)",
                epoch + 1, args.epochs, avg_train_loss, avg_val_loss,
                val_acc * 100.0, lr, elapsed,
            );
        } else {
            println!(
                "Epoch {:3}/{}: train_loss={:.4} val_loss={:.4} val_acc={:.2}% ({:.1}s)",
                epoch + 1, args.epochs, avg_train_loss, avg_val_loss,
                val_acc * 100.0, elapsed,
            );
        }

        // Save checkpoint
        let ckpt_path = format!("{}/epoch_{}.safetensors", args.checkpoint_dir, epoch + 1);
        trainer.save_checkpoint(&ckpt_path).unwrap();

        // Save best model
        if (avg_val_loss as f32) < best_val_loss {
            best_val_loss = avg_val_loss as f32;
            if let Some(parent) = std::path::Path::new(&args.output).parent() {
                std::fs::create_dir_all(parent).ok();
            }
            trainer.export_binary(&args.output).unwrap();
            println!("  → New best model saved to {} (val_loss={:.4})", args.output, best_val_loss);
        }
    }

    println!("\nTraining complete. Best val_loss={:.4}", best_val_loss);
    println!("Model saved to {}", args.output);
}

/// Build observation batch for the model (handles V1 vs V2 assembly).
///
/// For V1: just copies the 330-float obs directly.
/// For V2: assembles 414-float obs from V1 blocks + hard constraints.
fn build_obs_batch(dataset: &Dataset, indices: &[usize], v2: bool) -> Vec<f32> {
    if !v2 {
        // V1: straight copy
        let mut result = Vec::with_capacity(indices.len() * BELIEF_OBS_DIM);
        for &idx in indices {
            let start = idx * BELIEF_OBS_DIM;
            result.extend_from_slice(&dataset.obs[start..start + BELIEF_OBS_DIM]);
        }
        return result;
    }

    // V2: assemble 414-float obs from V1 obs (330) + hard constraints (96)
    let hc = dataset.hard_constraints.as_ref().expect("V2 requires hard_constraints");
    let mut result = Vec::with_capacity(indices.len() * BELIEF_OBS_DIM_V2);

    for &idx in indices {
        let obs_start = idx * BELIEF_OBS_DIM;
        let hc_start = idx * 96;

        // Blocks 1-6 from V1 obs [0..304]
        result.extend_from_slice(&dataset.obs[obs_start..obs_start + 304]);
        // Block 7: hard constraints (96 floats)
        result.extend_from_slice(&hc[hc_start..hc_start + 96]);
        // Blocks 8-11 from V1 obs [316..330] (skip V1 block 7 = voids [304..316])
        result.extend_from_slice(&dataset.obs[obs_start + 316..obs_start + BELIEF_OBS_DIM]);
    }

    result
}

/// Build an augmented batch: for each sample, apply a random suit permutation.
fn build_augmented_batch(
    dataset: &Dataset,
    indices: &[usize],
    v2: bool,
    rng: &mut StdRng,
) -> (Vec<f32>, Vec<u8>, Vec<u32>) {
    let obs_dim = if v2 { BELIEF_OBS_DIM_V2 } else { BELIEF_OBS_DIM };
    let mut obs_batch = Vec::with_capacity(indices.len() * obs_dim);
    let mut target_batch = Vec::with_capacity(indices.len() * 32);
    let mut mask_batch = Vec::with_capacity(indices.len());

    let hc = dataset.hard_constraints.as_ref();

    for &idx in indices {
        // Pick random permutation
        let perm_idx = rng.gen_range(0..24);
        let perm = &suit_perm::ALL_PERMS[perm_idx];

        // Build obs (V1 or V2)
        let obs_start = idx * BELIEF_OBS_DIM;
        let mut obs = if v2 {
            let hc_data = hc.expect("V2 requires hard_constraints");
            let hc_start = idx * 96;
            let mut buf = Vec::with_capacity(BELIEF_OBS_DIM_V2);
            buf.extend_from_slice(&dataset.obs[obs_start..obs_start + 304]);
            buf.extend_from_slice(&hc_data[hc_start..hc_start + 96]);
            buf.extend_from_slice(&dataset.obs[obs_start + 316..obs_start + BELIEF_OBS_DIM]);
            buf
        } else {
            dataset.obs[obs_start..obs_start + BELIEF_OBS_DIM].to_vec()
        };

        // Copy target
        let target_start = idx * 32;
        let mut target: [u8; 32] = dataset.targets[target_start..target_start + 32]
            .try_into().unwrap();

        // Copy mask
        let mut mask = dataset.masks[idx];

        // Apply permutation (skip identity)
        if perm_idx != 0 {
            if v2 {
                suit_perm::permute_belief_obs_v2(&mut obs, perm);
            } else {
                suit_perm::permute_belief_obs_v1(&mut obs, perm);
            }
            suit_perm::permute_target(&mut target, perm);
            mask = suit_perm::permute_mask(mask, perm);
        }

        obs_batch.extend_from_slice(&obs);
        target_batch.extend_from_slice(&target);
        mask_batch.push(mask);
    }

    (obs_batch, target_batch, mask_batch)
}

fn extract_targets(dataset: &Dataset, indices: &[usize]) -> Vec<u8> {
    let mut result = Vec::with_capacity(indices.len() * 32);
    for &idx in indices {
        let start = idx * 32;
        result.extend_from_slice(&dataset.targets[start..start + 32]);
    }
    result
}

fn extract_masks(dataset: &Dataset, indices: &[usize]) -> Vec<u32> {
    indices.iter().map(|&idx| dataset.masks[idx]).collect()
}
